export const dakarData = {
  slug: "dakar-biennale-2026",
  hero: {
    mastheadImage: "https://wakilisha.africa/wp-content/plugins/wakilisha-v2.0.201-cpt-cleanup/images/guides/dakar-biennale-2026/WAKILISHA_Dakar_Biennale_2026.jpg",
    badge: "Issue 002 · Advance dossier",
    kicker: "Dak’Art | The 16th Dakar Biennale",
    title: "(Anti)",
    titleItalic: "fragility",
    subtitle: "19 November to 19 December 2026 · Dakar, Senegal",
    facts: [
      { label: "Artistic Director", value: "Morad Montazami" },
      { label: "Edition", value: "16th Biennale" },
      { label: "Duration", value: "31 days" },
      { label: "Open to", value: "African artists and diaspora" },
    ],
    actions: [
      { label: "Read the dossier", href: "#dossier", primary: true },
      { label: "Follow Dakar 2026", href: "#updates", primary: false },
    ],
  },
  share: {
    url: "https://wakilisha.africa/guides/dakar-biennale-2026/",
    title: "Dak’Art 2026 | WAKILISHA Advance Dossier",
    description: "The WAKILISHA advance dossier for Dak’Art 2026, the 16th Dakar Biennale of Contemporary African Art.",
  },
  argument: {
    label: "01 · The argument",
    title: "Fragility is not the opposite of",
    titleItalic: "force",
    prose: [
      "Dak’Art 2026 is not framing fragility as weakness. Its concept turns the crack, the wound, the accident, the lack, the shelter and the repaired object into artistic material. The useful word is not resilience alone. It is transformation.",
      "The artistic direction names Morad Montazami as the conceptual lead. The early dossier gives WAKILISHA a live reporting frame before the Q4 opening, with attention on repair, care, language, scarcity, infrastructure and cultural value.",
    ],
    chaptersLabel: "Theme chapters",
    chapters: [
      { number: "01", title: "The Powers of the Fragile", description: "Small details, organic forms, cracks, fissures and everyday presence. Starting from what breaks rather than what holds." },
      { number: "02", title: "The Arts of Care and Repair", description: "Healing, preserving, rehabilitating invisible signs and languages. Artistic practice as maintenance and ethical attention." },
      { number: "03", title: "Counter-Shock Strategies", description: "Recycling, solidarity, short supply chains and crisis imagination. Building from scarcity and instability rather than despite it." },
    ],
  },
  anatomy: {
    label: "02 · Event architecture",
    title: "The Biennale is already",
    titleItalic: "more than one exhibition",
    items: [
      { number: "01", name: "Official International Exhibition", description: "African artists and diaspora artists selected through the official process. The spine of the edition, curated under Montazami’s direction.", route: "Primary route" },
      { number: "02", name: "National Pavilions", description: "Country-led presences that turn Dak’Art into a map of institutions, diplomacy and cultural strategy.", route: "Institutional route" },
      { number: "03", name: "Thematic and Tribute Exhibitions", description: "Curated arguments, memory work and homage formats that widen the field beyond the main selection.", route: "Context route" },
      { number: "04", name: "Special Projects", description: "Large-scale projects by artists, galleries, museums and institutions. The programmes with the most institutional independence.", route: "Independent route" },
      { number: "05", name: "Scientific and Professional Meetings", description: "The thinking layer: talks, research, publishing and art-sector infrastructure. Dak’Art positions itself as a knowledge event, not only an art fair.", route: "Knowledge route" },
      { number: "06", name: "Off Exhibitions and Collateral Events", description: "The city-facing layer. Private initiatives, labelled collateral events and environmental projects across Dakar.", route: "City route" },
    ],
  },
  disciplines: {
    label: "03 · Practice field",
    title: "Disciplines",
    titleItalic: "in play",
    note: "Eligible categories per the official international call",
    items: [
      { number: "01", name: "Architecture" },
      { number: "02", name: "Digital arts" },
      { number: "03", name: "Design" },
      { number: "04", name: "Installation" },
      { number: "05", name: "Mixed media" },
      { number: "06", name: "Painting" },
      { number: "07", name: "Performance" },
      { number: "08", name: "Photography" },
      { number: "09", name: "Sculpture" },
      { number: "10", name: "Sound" },
      { number: "11", name: "Street-art / Graffiti" },
      { number: "12", name: "Video art and animation" },
    ],
  },
  watchlist: {
    label: "04 · WAKILISHA watchlist",
    title: "What to report",
    titleItalic: "before Q4",
    items: [
      { number: "01", signal: "Care as infrastructure", question: "Who is building the systems that hold artists up?", body: "The theme gives us permission to look beyond objects into workshops, schools, collectives, archives, clinics of repair, mutual aid and the slow labour behind cultural survival." },
      { number: "02", signal: "Languages restored", question: "Which invisible signs return to public life?", body: "The concept explicitly opens a route into signs and languages made invisible. That makes language, translation, notation and oral knowledge central reporting ground." },
      { number: "03", signal: "Shock strategy", question: "How do artists work after crisis?", body: "Recycling, short supply chains and local knowledge are not side notes. They are ways to read artistic intelligence in a continent shaped by instability, scarcity and invention." },
      { number: "04", signal: "Market and memory", question: "Where does value move?", body: "Dak’Art's mandate includes international visibility and the contemporary African art market. The question is not only who is shown, but who gains infrastructure from being shown." },
    ],
  },
  timeline: {
    label: "05 · Calendar",
    title: "The timeline",
    titleItalic: "so far",
    note: "Updated as confirmed dates are released",
    events: [
      { date: "15 Apr 2026", event: "Official call and internal regulations issued in Dakar." },
      { date: "15 Apr to 15 Jun 2026", event: "Application window for the official international exhibition." },
      { date: "After selection", event: "Selected works must be ready within the preparation window set by the Secretariat." },
      { date: "19 Nov 2026", event: "Official opening and prize presentation ceremony." },
      { date: "19 Dec 2026", event: "Closing date of the sixteenth edition." },
    ],
  },
  follow: {
    label: "Follow the dossier",
    title: "We will update this as",
    titleItalic: "the field opens.",
    copy: [
      "This is not the final guide. It is the living pre-event page: confirmed facts, early readings, reporting angles and useful routes before the programme becomes public in full.",
      "When the full artist list, pavilion programmes, and WAKILISHA on-the-ground coverage are ready, subscribers receive them first.",
    ],
    form: {
      heading: "Get Dak’Art updates",
      description: "Dates, selected artists, pavilions, off routes, interviews and the full WAKILISHA guide when it is ready.",
      emailLabel: "Email address",
      emailPlaceholder: "you@example.com",
      personaLabel: "What are you tracking?",
      personaOptions: [
        { value: "", label: "Choose one" },
        { value: "artist", label: "Artist / curator" },
        { value: "collector", label: "Collector / patron" },
        { value: "institution", label: "Institution / funder" },
        { value: "writer", label: "Writer / researcher" },
        { value: "traveller", label: "Cultural traveller" },
      ],
      consentLabel: "Send me WAKILISHA field guide updates.",
      submitLabel: "Follow Dakar 2026",
    },
  },
};

export type DakarData = typeof dakarData;