import type { SVGProps } from "react";
import spriteUrl from "../../assets/icons/wakilisha-lucide.svg?url";

export type WkIconName =
  | "Accessibility"
  | "Activity"
  | "Airplay"
  | "Album"
  | "AlertCircle"
  | "AlertTriangle"
  | "Anchor"
  | "Antenna"
  | "Apple"
  | "Archive"
  | "ArchiveRestore"
  | "ArrowDown"
  | "ArrowDownRight"
  | "ArrowLeft"
  | "ArrowRight"
  | "ArrowUp"
  | "ArrowUpRight"
  | "AtSign"
  | "AudioLines"
  | "BadgeCheck"
  | "BarChart"
  | "BarChart2"
  | "BarChart3"
  | "Bell"
  | "Bold"
  | "Bookmark"
  | "BookMarked"
  | "BookOpen"
  | "BookOpenCheck"
  | "Braces"
  | "Briefcase"
  | "Building"
  | "Building2"
  | "Calendar"
  | "CalendarCheck"
  | "CalendarClock"
  | "CalendarDays"
  | "CalendarRange"
  | "CalendarX"
  | "CalendarX2"
  | "Camera"
  | "Captions"
  | "ChartNoAxesColumnIncreasing"
  | "Check"
  | "CheckCircle"
  | "CheckCircle2"
  | "CheckSquare"
  | "ChevronDown"
  | "ChevronLeft"
  | "ChevronRight"
  | "ChevronsLeft"
  | "ChevronsRight"
  | "ChevronUp"
  | "Chrome"
  | "Circle"
  | "CircleAlert"
  | "CirclePlus"
  | "Clapperboard"
  | "Clipboard"
  | "ClipboardCheck"
  | "ClipboardList"
  | "Clock"
  | "Clock3"
  | "Cloud"
  | "CloudUpload"
  | "Code"
  | "Code2"
  | "Command"
  | "Compass"
  | "Contact"
  | "Copy"
  | "Copyright"
  | "CornerDownLeft"
  | "Crown"
  | "Database"
  | "Delete"
  | "Disc"
  | "Disc3"
  | "Download"
  | "Drill"
  | "Edit"
  | "Edit3"
  | "Ellipsis"
  | "Eraser"
  | "Expand"
  | "ExternalLink"
  | "Eye"
  | "EyeOff"
  | "Facebook"
  | "File"
  | "FileCode"
  | "FileEdit"
  | "FilePenLine"
  | "FileText"
  | "FileX"
  | "Film"
  | "Filter"
  | "Fingerprint"
  | "Flag"
  | "Flame"
  | "FlaskConical"
  | "Focus"
  | "Folder"
  | "FolderPlus"
  | "FolderTree"
  | "Frame"
  | "Funnel"
  | "Gauge"
  | "GitBranch"
  | "GitCommit"
  | "GitCommitHorizontal"
  | "GitCompare"
  | "GitMerge"
  | "GitPullRequest"
  | "Globe"
  | "Globe2"
  | "Grid2x2"
  | "GripVertical"
  | "Group"
  | "Hand"
  | "Hash"
  | "Heading1"
  | "Heading2"
  | "Heading3"
  | "Heart"
  | "HeartPulse"
  | "HelpCircle"
  | "History"
  | "Home"
  | "Image"
  | "ImageOff"
  | "ImagePlus"
  | "Images"
  | "Inbox"
  | "Indent"
  | "Info"
  | "Instagram"
  | "Italic"
  | "Key"
  | "KeyRound"
  | "Layers"
  | "Layers3"
  | "Layout"
  | "LayoutDashboard"
  | "LayoutGrid"
  | "LayoutList"
  | "Library"
  | "Lightbulb"
  | "LineChart"
  | "Link"
  | "Link2"
  | "List"
  | "ListChecks"
  | "ListFilter"
  | "ListMusic"
  | "ListOrdered"
  | "ListPlus"
  | "ListTree"
  | "ListVideo"
  | "Loader"
  | "Loader2"
  | "LoaderCircle"
  | "Lock"
  | "LockKeyhole"
  | "LogIn"
  | "LogOut"
  | "Mail"
  | "MailCheck"
  | "Map"
  | "MapPin"
  | "MapPinned"
  | "Maximize2"
  | "Menu"
  | "Merge"
  | "MessageCircle"
  | "MessageCirclePlus"
  | "MessageSquare"
  | "MessageSquareMore"
  | "MessageSquarePlus"
  | "MessageSquareText"
  | "MessageSquareWarning"
  | "MessagesSquare"
  | "Mic2"
  | "MicVocal"
  | "Minimize2"
  | "Minus"
  | "MinusCircle"
  | "Monitor"
  | "Moon"
  | "MoreHorizontal"
  | "MoreVertical"
  | "MousePointerClick"
  | "MoveDown"
  | "Music"
  | "Music2"
  | "Navigation"
  | "Network"
  | "Newspaper"
  | "NotebookText"
  | "Outdent"
  | "Palette"
  | "PanelLeftClose"
  | "PanelLeftOpen"
  | "PanelRight"
  | "PanelRightOpen"
  | "PanelsTopLeft"
  | "PanelTop"
  | "Pause"
  | "Pencil"
  | "PencilLine"
  | "PenLine"
  | "Phone"
  | "Pin"
  | "PinOff"
  | "Play"
  | "PlayCircle"
  | "Plug"
  | "Plus"
  | "PlusCircle"
  | "Podcast"
  | "Quote"
  | "Radar"
  | "Radio"
  | "RadioTower"
  | "Radius"
  | "Redo"
  | "Redo2"
  | "RefreshCcw"
  | "RefreshCw"
  | "RemoveFormatting"
  | "Repeat"
  | "Repeat1"
  | "Repeat2"
  | "Reply"
  | "Rocket"
  | "RotateCcw"
  | "RotateCw"
  | "Route"
  | "Rows"
  | "Rss"
  | "Save"
  | "Scale"
  | "ScanText"
  | "Search"
  | "SearchCheck"
  | "SearchX"
  | "Section"
  | "Send"
  | "SendHorizontal"
  | "Settings"
  | "Settings2"
  | "Share"
  | "Share2"
  | "Sheet"
  | "Shell"
  | "Shield"
  | "ShieldAlert"
  | "ShieldCheck"
  | "ShieldOff"
  | "Shuffle"
  | "Signal"
  | "Siren"
  | "SkipBack"
  | "SkipForward"
  | "SlidersHorizontal"
  | "Smartphone"
  | "Sparkles"
  | "Split"
  | "Square"
  | "Star"
  | "Strikethrough"
  | "Sun"
  | "Tag"
  | "Tags"
  | "Target"
  | "TestTube2"
  | "Text"
  | "Trash2"
  | "TrendingDown"
  | "TrendingUp"
  | "TriangleAlert"
  | "Twitter"
  | "Type"
  | "Underline"
  | "Undo"
  | "Undo2"
  | "Unlink"
  | "Upload"
  | "UploadCloud"
  | "User"
  | "User2"
  | "UserCheck"
  | "UserMinus"
  | "UserPlus"
  | "UserRound"
  | "UserRoundX"
  | "Users"
  | "UsersRound"
  | "UserX"
  | "Verified"
  | "Video"
  | "View"
  | "Volume"
  | "Volume1"
  | "Volume2"
  | "VolumeX"
  | "Wand"
  | "Watch"
  | "Weight"
  | "Wifi"
  | "Workflow"
  | "Wrench"
  | "X"
  | "XCircle"
  | "Zap"
  | "ZoomIn";

type WkIconProps = SVGProps<SVGSVGElement> & {
  name: WkIconName;
  size?: number;
  strokeWidth?: number;
};

function iconId(name: WkIconName): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Za-z])([0-9])/g, "$1-$2")
    .replace(/([0-9])([A-Za-z])/g, "$1-$2")
    .toLowerCase();
}

export function WkIcon({
  name,
  size = 18,
  strokeWidth = 2,
  ...props
}: WkIconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      focusable="false"
      {...props}
    >
      <use
        href={`${spriteUrl}#wk-lucide-${iconId(name)}`}
      />
    </svg>
  );
}
