import type { Config } from "tailwindcss";

export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--wk-font-display)", "Inter", "system-ui", "sans-serif"],
        body: ["var(--wk-font-body)", "DM Sans", "Inter", "system-ui", "sans-serif"],
        ui: ["var(--wk-font-ui)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--wk-font-mono)", "DM Mono", "ui-monospace", "monospace"],
      },
      colors: {
        wk: {
          bg: "var(--wk-bg)",
          "bg-subtle": "var(--wk-bg-subtle)",
          surface: "var(--wk-surface)",
          "surface-raised": "var(--wk-surface-raised)",
          "surface-strong": "var(--wk-surface-strong)",
          text: "var(--wk-text)",
          "text-soft": "var(--wk-text-soft)",
          "text-muted": "var(--wk-text-muted)",
          "text-faint": "var(--wk-text-faint)",
          "text-on-brand": "var(--wk-text-on-brand)",
          "text-inverse": "var(--wk-text-inverse)",
          border: "var(--wk-border)",
          "border-2": "var(--wk-border-2)",
          "border-strong": "var(--wk-border-strong)",
          divider: "var(--wk-divider)",
          brand: "var(--wk-brand)",
          "brand-2": "var(--wk-brand-2)",
          "brand-soft": "var(--wk-brand-soft)",
          "brand-on": "var(--wk-brand-on)",
          success: "var(--wk-success)",
          "success-soft": "var(--wk-success-soft)",
          warning: "var(--wk-warning)",
          "warning-soft": "var(--wk-warning-soft)",
          danger: "var(--wk-danger)",
          "danger-soft": "var(--wk-danger-soft)",
          info: "var(--wk-info)",
          "info-soft": "var(--wk-info-soft)",
        },
      },
      borderRadius: {
        "wk-1": "var(--wk-r-1)",
        "wk-2": "var(--wk-r-2)",
        "wk-3": "var(--wk-r-3)",
        "wk-4": "var(--wk-r-4)",
        "wk-5": "var(--wk-r-5)",
        "wk-6": "var(--wk-r-6)",
        "wk-7": "var(--wk-r-7)",
        "wk-pill": "var(--wk-r-pill)",
      },
      transitionDuration: {
        "wk-instant": "var(--wk-d-instant)",
        "wk-fast": "var(--wk-d-fast)",
        "wk-standard": "var(--wk-d-standard)",
        "wk-slow": "var(--wk-d-slow)",
        "wk-deliberate": "var(--wk-d-deliberate)",
      },
      transitionTimingFunction: {
        "wk-standard": "var(--wk-ease-standard)",
        "wk-snap": "var(--wk-ease-snap)",
        "wk-in": "var(--wk-ease-in)",
        "wk-out": "var(--wk-ease-out)",
      },
      maxWidth: {
        "wk-narrow": "var(--wk-w-narrow)",
        "wk-text": "var(--wk-w-text)",
        "wk-content": "var(--wk-w-content)",
        "wk-wide": "var(--wk-w-wide)",
        "wk-max": "var(--wk-w-max)",
      },
    },
  },
  plugins: [],
} satisfies Config;