import type { WkDesignChapterSpec } from '../designSystemSpecTypes';

export const reactAppUIChapters: WkDesignChapterSpec[] = [
  {
    id: 'hero-sections',
    number: '35',
    group: 'React App UI',
    title: 'Hero Sections',
    summary: 'Page heroes for magazine, charts, directories, artists, tracks, releases, and admin. Hero scale matches content importance: directory heroes are smaller than editorial heroes. Scrims for photography preserve text contrast. Hero actions are specific and graph-backed.',
    adminSections: ['Hero preview panel', 'Hero scale tester', 'Admin hero builder'],
    implementationRules: [
      'Hero scale must match content importance; directory heroes are not as large as editorial heroes.',
      'Use scrims for photography and preserve text contrast.',
      'Hero actions must be specific and graph-backed.',
      'Hero must support dark, light, and photo backgrounds.',
      'Admin hero is smaller and carries breadcrumb + action bar.',
    ],
    componentsRequired: ['WkPageHero', 'WkMagazineHero', 'WkChartHero', 'WkEntityHero', 'WkAdminHero'],
    tables: [],
    parityTargets: ['Build PageHero, MagazineHero, ChartHero, EntityHero, AdminHero.', 'All heroes use the PageHero primitive with variant prop.'],
    qaChecks: [
      { id: '35-scale-appropriate', label: 'Scale appropriate', description: 'Hero size matches content importance.' },
      { id: '35-scrim-legible', label: 'Scrim legible', description: 'Hero text is legible on all backgrounds.' },
      { id: '35-actions-specific', label: 'Specific actions', description: 'Hero CTAs are specific and graph-backed.' },
    ],
  },
  {
    id: 'genre-directory',
    number: '36',
    group: 'React App UI',
    title: 'Genre Directory',
    summary: 'Genres as a discovery surface with artist/track counts and visual cards. Genre cards show name, counts, and representative artists/tracks. No unrelated stock images as genre art. Genre pages route into graph-backed artist/track lists.',
    adminSections: ['Genre card preview', 'Genre route tester', 'Genre count audit'],
    implementationRules: [
      'Genre cards must show name, counts, representative artists/tracks where available.',
      'Do not use unrelated stock images as permanent genre art.',
      'Genre pages should route into graph-backed artist/track lists.',
      'Genre directory supports grid, list, and filter views.',
      'Genre data must come from artist_genres and entity relationships.',
    ],
    componentsRequired: ['WkGenreCard', 'WkGenreGrid', 'WkGenreFilter', 'WkGenreDirectory'],
    tables: ['artist_genres', 'entity_relationships'],
    parityTargets: ['Build /genres and /genres/:slug from artist_genres and entity relationships.', 'Genre directory is graph-backed.'],
    qaChecks: [
      { id: '36-counts', label: 'Counts shown', description: 'Genre cards show artist and track counts.' },
      { id: '36-no-stock', label: 'No stock images', description: 'Genre art is not unrelated stock photos.' },
      { id: '36-graph-backed', label: 'Graph-backed', description: 'Genre data comes from artist_genres and relationships.' },
    ],
  },
  {
    id: 'artist-directory',
    number: '37',
    group: 'React App UI',
    title: 'Artist Directory',
    summary: 'Artists feel culturally important, not like database rows. Artist cards need image, name, genres, track/release counts, and chart context. Directory supports grid/list, search, filters, and alphabetic index. Full artist index exists but is not the main emotional experience.',
    adminSections: ['Artist card preview', 'Directory layout tester', 'Search/filter audit'],
    implementationRules: [
      'Artist cards need image, name, genres, track/release counts, and chart context where available.',
      'Directory supports grid/list, search, filters, and alphabetic index.',
      'Full artist index can exist, but not as the main emotional experience.',
      'Artist data must come from entity_slugs and track_artists.',
      'Artist pages must expose tracks, releases, and chart appearances.',
    ],
    componentsRequired: ['WkArtistCard', 'WkArtistGrid', 'WkArtistDirectory', 'WkArtistFilter'],
    tables: ['entity_slugs', 'track_artists', 'entity_relationships'],
    parityTargets: ['Build /artists and /artists/:slug from entity_slugs + track_artists.', 'Artist directory is graph-backed and relationship-aware.'],
    qaChecks: [
      { id: '37-culturally-important', label: 'Culturally important', description: 'Artists feel like cultural figures, not database rows.' },
      { id: '37-grid-list', label: 'Grid + list', description: 'Directory supports grid and list views.' },
      { id: '37-relationships', label: 'Relationships', description: 'Artist pages expose tracks, releases, and charts.' },
    ],
  },
  {
    id: 'magazine-page',
    number: '38',
    group: 'React App UI',
    title: 'Magazine Page',
    summary: 'An authored editorial surface, not a generic blog grid. Magazine needs feature story, sections, story cards, editorial metadata, and related graph embeds. Content classification excludes app shells and utility pages. Article cards have section/category, date, reading time, and real routes.',
    adminSections: ['Magazine preview', 'Article card builder', 'Content classification panel', 'Story editor'],
    implementationRules: [
      'Magazine needs feature story, sections, story cards, editorial metadata, and related graph embeds.',
      'Use content classification to exclude app shells and utility pages.',
      'Article cards need section/category, date, reading time when available, and real routes.',
      'Magazine index must support featured story + section grids.',
      'Article body must use --wk-w-text for reading width.',
    ],
    componentsRequired: ['WkStoryCard', 'WkMagazineIndex', 'WkArticlePage', 'WkArticleBody', 'WkArticleHero'],
    tables: ['content_route_classification'],
    parityTargets: ['Build /magazine and /magazine/:slug from content classification.', 'Magazine is editorial-first and graph-backed.'],
    qaChecks: [
      { id: '38-editorial', label: 'Editorial feel', description: 'Magazine feels authored, not a generic blog grid.' },
      { id: '38-classified', label: 'Classified', description: 'Content classification separates editorial from utility.' },
      { id: '38-real-routes', label: 'Real routes', description: 'Article cards link to real article pages.' },
    ],
  },
  {
    id: 'charts-edition',
    number: '39',
    group: 'React App UI',
    title: 'Charts Edition',
    summary: 'Chart editions are the signature product surface. Chart rows are dense, ranked, expandable, playable when possible, and linked to canonical entities. Chart headers show edition metadata, methodology/status, and stats. Movement/history is not fabricated when data is unavailable.',
    adminSections: ['Chart edition preview', 'Chart row builder', 'Series manager', 'Methodology editor'],
    implementationRules: [
      'Chart rows must be dense, ranked, expandable, playable when possible, and linked to canonical entities.',
      'Chart headers show edition metadata, methodology/status, and stats.',
      'Movement/history UI must not be fabricated if data is unavailable.',
      'Chart editions must support multiple series and weekly cadence.',
      'Chart data must come from chart_entries and entity relationships.',
    ],
    componentsRequired: ['WkChartEdition', 'WkChartHeader', 'WkChartRow', 'WkChartMovement', 'WkChartHistory'],
    tables: ['chart_entries', 'entity_relationships'],
    parityTargets: ['Build /charts, /charts/:series, /charts/:series/:edition.', 'Chart editions are the signature product surface.'],
    qaChecks: [
      { id: '39-dense', label: 'Dense rows', description: 'Chart rows are dense and information-rich.' },
      { id: '39-playable', label: 'Playable', description: 'Chart rows are playable when preview is available.' },
      { id: '39-no-fabricated', label: 'No fabricated data', description: 'Movement and history are not fabricated.' },
    ],
  },
  {
    id: 'single-track',
    number: '40',
    group: 'React App UI',
    title: 'Single Track',
    summary: 'Graph-powered track detail pages with playback, chart history, release links, and credits. Track page pulls artists, playback sources, release relationships, media, chart appearances, and route metadata. Play button only appears enabled when preview is available. ISRC/source/provider attribution visible.',
    adminSections: ['Track preview', 'Playback source audit', 'Chart history viewer', 'Relationship module'],
    implementationRules: [
      'Track page pulls artists, playback sources, release relationships, media, chart appearances, and route metadata.',
      'Play button only appears enabled when preview/playback is available.',
      'ISRC/source/provider attribution must be visible when available.',
      'Track metadata must be graph-backed, not hard-coded.',
      'Track pages must expose related tracks, chart appearances, and release history.',
    ],
    componentsRequired: ['WkTrackPage', 'WkTrackHero', 'WkTrackMeta', 'WkTrackRelationships', 'WkPlaybackSource'],
    tables: ['track_playback_sources', 'entity_relationships', 'chart_entries'],
    parityTargets: ['Build /tracks/:slug payload and page.', 'Track pages are graph-powered and relationship-aware.'],
    qaChecks: [
      { id: '40-graph-backed', label: 'Graph-backed', description: 'Track data comes from the repaired graph.' },
      { id: '40-playback-enabled', label: 'Playback enabled', description: 'Play button is disabled when no preview is available.' },
      { id: '40-attribution', label: 'Attribution', description: 'ISRC and source attribution are visible.' },
    ],
  },
  {
    id: 'single-album',
    number: '41',
    group: 'React App UI',
    title: 'Single Album',
    summary: 'Release pages with cover, metadata, tracklist, label, artists, and related graph modules. Release tracklist comes from release_tracks. Modal and page patterns are consistent for album detail. Duplicate/review release states are not flattened into public certainty.',
    adminSections: ['Release preview', 'Tracklist builder', 'Release relationship audit', 'Duplicate state manager'],
    implementationRules: [
      'Release tracklist must come from release_tracks.',
      'Use modal and page patterns consistently for album detail.',
      'Do not flatten duplicate/review release states into public certainty.',
      'Release pages must expose label, artists, chart activity, and related releases.',
      'Release cover art must use the media resolver with fallback.',
    ],
    componentsRequired: ['WkReleasePage', 'WkReleaseHero', 'WkReleaseTracklist', 'WkReleaseMeta', 'WkReleaseRelationships'],
    tables: ['release_tracks', 'entity_relationships', 'track_playback_sources'],
    parityTargets: ['Build /releases/:slug payload and page.', 'Release pages are graph-backed and tracklist-accurate.'],
    qaChecks: [
      { id: '41-tracklist-accurate', label: 'Tracklist accurate', description: 'Tracklist comes from release_tracks, not hard-coded.' },
      { id: '41-modal-consistent', label: 'Modal consistent', description: 'Album modal and page use the same design language.' },
      { id: '41-no-flatten', label: 'No flatten', description: 'Duplicate/review states are not flattened into public certainty.' },
    ],
  },
  {
    id: 'album-modal',
    number: '42',
    group: 'React App UI',
    title: 'Album Modal',
    summary: 'Quick release preview without leaving context. Modal traps focus and respects reduced motion. Shows cover, metadata, tracklist preview, actions, share, and source attribution. Never duplicates a separate design language from the release page.',
    adminSections: ['Modal preview', 'Focus trap tester', 'Modal component gallery'],
    implementationRules: [
      'Modal must trap focus and respect reduced motion.',
      'Shows cover, metadata, tracklist preview, actions, share, and source attribution.',
      'Never duplicate a separate design language from the release page.',
      'Modal must close on Escape and backdrop click.',
      'Modal must restore focus to the trigger element on close.',
    ],
    componentsRequired: ['WkModal', 'WkReleaseQuickView', 'WkReleaseModalContent'],
    tables: ['release_tracks'],
    parityTargets: ['Build ReleaseQuickView modal.', 'Modal reuses the same components as the release page.'],
    qaChecks: [
      { id: '42-focus-trap', label: 'Focus trap', description: 'Modal traps focus and supports keyboard navigation.' },
      { id: '42-reduced-motion', label: 'Reduced motion', description: 'Modal respects prefers-reduced-motion.' },
      { id: '42-same-language', label: 'Same design language', description: 'Modal does not use a different design language from the page.' },
    ],
  },
  {
    id: 'labels-directory',
    number: '43',
    group: 'React App UI',
    title: 'Labels Directory',
    summary: 'Labels as a serious industry registry, not a plain list. Label cards show releases, artists, country/metadata, and featured status. Label pages expose releases, artists, and chart activity. Repaired label/release relationships are used.',
    adminSections: ['Label card preview', 'Label relationship audit', 'Registry completeness report'],
    implementationRules: [
      'Label cards show releases, artists, country/metadata, and featured status if available.',
      'Label pages expose releases, artists, and chart activity.',
      'Use repaired label/release relationships.',
      'Label directory supports grid, list, and filter views.',
      'Label metadata must come from entity_slugs and entity_relationships.',
    ],
    componentsRequired: ['WkLabelCard', 'WkLabelDirectory', 'WkLabelPage', 'WkLabelMeta'],
    tables: ['entity_slugs', 'entity_relationships', 'release_tracks'],
    parityTargets: ['Build /labels and /labels/:slug.', 'Label directory is graph-backed and industry-credible.'],
    qaChecks: [
      { id: '43-serious-registry', label: 'Serious registry', description: 'Labels feel like an industry directory, not a plain list.' },
      { id: '43-relationships', label: 'Relationships', description: 'Label pages expose releases, artists, and chart activity.' },
      { id: '43-repaired', label: 'Repaired graph', description: 'Label data uses repaired label/release relationships.' },
    ],
  },
  {
    id: 'article-post',
    number: '44',
    group: 'React App UI',
    title: 'Article / Post',
    summary: 'Article pages with reading rhythm, related entities, and credibility markers. Article body width uses --wk-w-text. Hero and byline placement support editorial credibility. Related tracks/artists/articles come from graph/content metadata when available.',
    adminSections: ['Article preview', 'Reading rhythm tester', 'Related entity embedder', 'Byline builder'],
    implementationRules: [
      'Article body width must use --wk-w-text.',
      'Hero and byline placement must support editorial credibility.',
      'Related tracks/artists/articles should come from graph/content metadata when available.',
      'Article pages must support rich text, inline entities, and media embeds.',
      'Article date and author must be visible and accurate.',
    ],
    componentsRequired: ['WkArticlePage', 'WkArticleBody', 'WkArticleHero', 'WkArticleByline', 'WkRelatedEntities'],
    tables: ['content_route_classification', 'entity_relationships'],
    parityTargets: ['Build article page archetype and embedded entity cards.', 'Articles are graph-aware and editorially credible.'],
    qaChecks: [
      { id: '44-reading-width', label: 'Reading width', description: 'Article body uses --wk-w-text max-width.' },
      { id: '44-credible', label: 'Credible byline', description: 'Byline and date placement support editorial credibility.' },
      { id: '44-related-graph', label: 'Related graph', description: 'Related entities come from graph metadata when available.' },
    ],
  },
  {
    id: 'sharing-system',
    number: '45',
    group: 'React App UI',
    title: 'Sharing System',
    summary: 'Consistent share sheets, timestamp sharing, OG previews, and platform actions. Share previews reflect the actual entity/article being shared. Specific share copy, not generic link labels. Timestamp sharing available for playable media.',
    adminSections: ['Share preview panel', 'OG card tester', 'Share copy editor', 'Platform action audit'],
    implementationRules: [
      'Share previews must reflect the actual entity/article being shared.',
      'Use specific share copy, not generic link labels.',
      'Timestamp sharing is available for playable media.',
      'Share sheet must include copy link, platform actions, and entity preview.',
      'OG metadata must include title, description, image, and canonical URL.',
    ],
    componentsRequired: ['WkShareSheet', 'WkCopyLink', 'WkOGCardPreview', 'WkShareButton'],
    tables: [],
    parityTargets: ['Build ShareSheet, CopyLink, OGCardPreview.', 'Sharing is available on all entity and article pages.'],
    qaChecks: [
      { id: '45-specific-copy', label: 'Specific copy', description: 'Share copy is specific to the entity, not generic.' },
      { id: '45-og-preview', label: 'OG preview', description: 'OG card reflects the actual entity being shared.' },
      { id: '45-timestamp', label: 'Timestamp share', description: 'Timestamp sharing is available for playable media.' },
    ],
  },
  {
    id: 'iconography',
    number: '46',
    group: 'React App UI',
    title: 'Iconography',
    summary: 'Standardized icon size, weight, labels, and semantic use. Icons are supportive, not decorative clutter. Icon-only buttons need labels and 44px hit areas where touchable. Consistent 16/20/24px sizing. Remix Icon is the primary icon set.',
    adminSections: ['Icon gallery', 'Size/weight audit', 'Semantic use checker', 'Touch target tester'],
    implementationRules: [
      'Icons are supportive, not decorative clutter.',
      'Icon-only buttons need labels and 44px hit areas where touchable.',
      'Use consistent 16/20/24px icon sizing.',
      'Remix Icon is the primary icon set.',
      'Icons must have aria-labels or aria-hidden with accessible text.',
    ],
    componentsRequired: ['WkIcon', 'WkIconButton', 'WkIconGallery'],
    tables: [],
    parityTargets: ['Create icon wrapper and accessibility defaults.', 'All icons use consistent sizing and accessibility.'],
    qaChecks: [
      { id: '46-aria', label: 'ARIA labels', description: 'All icon-only buttons have aria-labels.' },
      { id: '46-touch-target', label: 'Touch targets', description: 'Icon buttons are at least 44x44px on touch.' },
      { id: '46-consistent-size', label: 'Consistent size', description: 'Icons use consistent 16/20/24px sizing.' },
    ],
  },
  {
    id: 'dark-light-mode',
    number: '47',
    group: 'React App UI',
    title: 'Dark / Light Mode',
    summary: 'Both themes are first-class using tokens. No dark-only hardcoded text or backgrounds. Logo variant, surface colors, brand color, and status colors switch via tokens. Images need overlays that preserve readability in both themes. Theme toggle is instant.',
    adminSections: ['Theme toggle', 'Theme preview panel', 'Token inspector', 'QA gate: theme compliance'],
    implementationRules: [
      'No dark-only hardcoded text or backgrounds.',
      'Logo variant, surface colors, brand color, and status colors must switch via tokens.',
      'Images need overlays that preserve readability in both themes.',
      'Theme toggle must be instant and persistent via localStorage.',
      'Theme must be set via data-wk-theme attribute on the root.',
    ],
    componentsRequired: ['ThemeProvider', 'TokenInspector', 'ThemeToggle'],
    tables: [],
    parityTargets: ['Theme provider with data-wk-theme and mode toggle.', 'All components render correctly in both themes.'],
    qaChecks: [
      { id: '47-instant', label: 'Instant switch', description: 'Theme switches instantly without page reload.' },
      { id: '47-token-driven', label: 'Token-driven', description: 'All theme-specific color is via tokens.' },
      { id: '47-persistent', label: 'Persistent', description: 'Theme preference persists across sessions.' },
    ],
  },
  {
    id: 'user-profile',
    number: '48',
    group: 'React App UI',
    title: 'User Profile',
    summary: 'User identity, follows, saves, collections, and listening/editorial activity. Profile surfaces use cover, avatar, stats, tabs, and activity modules. Social network behavior is not overbuilt until the product requires it. Privacy and public/private states are explicit.',
    adminSections: ['Profile preview', 'Privacy settings', 'Activity module tester', 'Follows audit'],
    implementationRules: [
      'Profile surfaces use cover, avatar, stats, tabs, and activity modules.',
      'Do not overbuild social network behavior until product requires it.',
      'Privacy and public/private states must be explicit.',
      'Profile data must come from auth/user tables.',
      'Activity modules must be scannable and date-ordered.',
    ],
    componentsRequired: ['WkProfileShell', 'WkProfileAvatar', 'WkProfileStats', 'WkProfileTabs', 'WkActivityModule'],
    tables: [],
    parityTargets: ['Build profile shell after public entity parity.', 'Profile is built after auth and user scope are defined.'],
    qaChecks: [
      { id: '48-privacy', label: 'Privacy explicit', description: 'Privacy and public/private states are clearly visible.' },
      { id: '48-no-overbuild', label: 'No overbuild', description: 'Social features are not overbuilt before product needs them.' },
    ],
  },
  {
    id: 'settings-pages',
    number: '49',
    group: 'React App UI',
    title: 'Settings Pages',
    summary: 'Clean settings surfaces for account, notifications, theme, privacy, and playback preferences. Sidebar/pane structure on desktop and stacked nav on mobile. Danger zones are visually distinct but restrained. Every toggle has label and description.',
    adminSections: ['Settings preview', 'Toggle builder', 'Danger zone preview', 'Privacy settings panel'],
    implementationRules: [
      'Settings use sidebar/pane structure on desktop and stacked nav on mobile.',
      'Danger zones are visually distinct but restrained.',
      'Every toggle has label and description.',
      'Settings must be persistent and immediately reflected.',
      'Theme toggle must be in settings as well as global nav.',
    ],
    componentsRequired: ['WkSettingsShell', 'WkSettingsPane', 'WkToggle', 'WkDangerZone', 'WkSettingsGroup'],
    tables: [],
    parityTargets: ['Build settings archetype after auth/user scope is defined.', 'Settings follow the same archetype pattern.'],
    qaChecks: [
      { id: '49-toggle-described', label: 'Toggle described', description: 'Every toggle has a label and description.' },
      { id: '49-danger-zone', label: 'Danger zone', description: 'Danger zones are visually distinct but restrained.' },
    ],
  },
  {
    id: 'admin-areas',
    number: '50',
    group: 'React App UI',
    title: 'Admin Areas',
    summary: 'Admin feels like an editorial/cultural operating system, not a backend afterthought. Admin has its own breadcrumb bar, KPI cards, review tables, and design-system browser. Design System Bible is browsable, searchable, theme-toggleable, and component-previewable inside admin. Admin uses the same tokens as public pages.',
    adminSections: ['Design System Bible', 'Review queue tables', 'KPI dashboard', 'Breadcrumb bar', 'Admin nav'],
    implementationRules: [
      'Admin has its own breadcrumb bar, KPI cards, review tables, and design-system browser.',
      'Design System Bible must be browsable, searchable, theme-toggleable, and component-previewable inside admin.',
      'Admin pages use the same tokens as public pages.',
      'Admin surfaces must not look like a different app.',
      'Admin KPI cards must show real data from review_queue and entity counts.',
    ],
    componentsRequired: ['AdminDesignSystem', 'AdminBar', 'AdminKpi', 'AdminTable', 'ReviewQueueTable'],
    tables: ['review_queue', 'entity_slugs', 'entity_relationships'],
    parityTargets: ['Build /admin/design-system as first admin feature.', 'Admin feels like an editorial OS, not a backend afterthought.'],
    qaChecks: [
      { id: '50-same-tokens', label: 'Same tokens', description: 'Admin uses the same tokens as public pages.' },
      { id: '50-bible', label: 'Design Bible', description: 'Admin design bible is browsable and searchable.' },
      { id: '50-not-backend', label: 'Not backend', description: 'Admin does not look like a generic CMS backend.' },
    ],
  },
  {
    id: 'notifications',
    number: '51',
    group: 'React App UI',
    title: 'Notifications',
    summary: 'Standardized notification panels and review/update alerts. Unread indicators use brand edge bar or dot, not loud banners. Notification copy is factual and specific. Admin review alerts link to exact review items.',
    adminSections: ['Notification panel', 'Review alert preview', 'Unread indicator tester', 'Notification history'],
    implementationRules: [
      'Unread indicators use brand edge bar or dot, not loud banners.',
      'Notification copy is factual and specific.',
      'Admin review alerts should link to exact review items.',
      'Notification panel must be dismissible and persistent.',
      'Notification count must be accurate and not misleading.',
    ],
    componentsRequired: ['WkNotificationPanel', 'WkNotificationBadge', 'WkReviewAlert', 'WkNotificationItem'],
    tables: ['review_queue'],
    parityTargets: ['Build NotificationPanel and AdminReviewNotifications.', 'Notifications are factual and specific.'],
    qaChecks: [
      { id: '51-restraint', label: 'Restrained', description: 'Notifications are restrained, not loud banners.' },
      { id: '51-specific', label: 'Specific copy', description: 'Notification copy is factual and specific.' },
      { id: '51-link', label: 'Link to review', description: 'Admin review alerts link to exact review items.' },
    ],
  },
  {
    id: 'modals-overlays',
    number: '52',
    group: 'React App UI',
    title: 'Modals & Overlays',
    summary: 'Sheets, modals, drawers, backdrops, and focus behavior. Modals trap focus, restore focus, and support Escape close. Sheets for mobile contextual actions, modals for desktop focus tasks. Overlay motion originates from trigger or dock.',
    adminSections: ['Modal gallery', 'Sheet preview', 'Focus trap tester', 'Motion audit panel'],
    implementationRules: [
      'Modals trap focus, restore focus, and support Escape close.',
      'Use sheets for mobile contextual actions and modals for desktop focus tasks.',
      'Overlay motion must originate from trigger or dock.',
      'Backdrop must be clickable to dismiss.',
      'Multiple modals must stack correctly and restore focus on close.',
    ],
    componentsRequired: ['WkModal', 'WkSheet', 'WkDrawer', 'WkOverlay', 'WkBackdrop'],
    tables: [],
    parityTargets: ['Build Modal, Sheet, Drawer, Overlay primitives.', 'All overlays trap focus and support reduced motion.'],
    qaChecks: [
      { id: '52-focus-trap', label: 'Focus trap', description: 'Modals trap focus and support keyboard navigation.' },
      { id: '52-escape', label: 'Escape close', description: 'Escape closes the modal.' },
      { id: '52-restore-focus', label: 'Restore focus', description: 'Focus is restored to the trigger on close.' },
    ],
  },
  {
    id: 'mobile-patterns',
    number: '53',
    group: 'React App UI',
    title: 'Mobile Patterns',
    summary: 'Mobile is designed intentionally, not as collapsed desktop. Horizontal scroll rows are used sparingly for discovery, not primary navigation. Mobile bottom nav coexists with player dock. Cards and rows have mobile-specific hierarchy, not just smaller desktop.',
    adminSections: ['Mobile preview panel', 'Bottom nav tester', 'Player coexistence', 'Horizontal scroll audit'],
    implementationRules: [
      'Use horizontal scroll rows sparingly for discovery, not primary navigation.',
      'Mobile bottom nav must coexist with player dock.',
      'Cards and rows need mobile-specific hierarchy, not just smaller desktop.',
      'Mobile navigation must be tappable with 44px hit areas.',
      'Mobile forms must stack vertically and use native inputs where appropriate.',
    ],
    componentsRequired: ['WkMobileNav', 'WkBottomNav', 'WkMobileCard', 'WkMobileRow', 'WkHorizontalScroll'],
    tables: [],
    parityTargets: ['Build mobile page variants for charts, directories, player, and magazine.', 'Mobile is first-class, not collapsed desktop.'],
    qaChecks: [
      { id: '53-intentional', label: 'Intentional', description: 'Mobile is designed intentionally, not collapsed desktop.' },
      { id: '53-player-coexist', label: 'Player coexistence', description: 'Bottom nav and player dock coexist without overlap.' },
      { id: '53-hit-area', label: 'Hit areas', description: 'Mobile controls are at least 44px.' },
    ],
  },
  {
    id: 'delight-animation',
    number: '54',
    group: 'React App UI',
    title: 'Delight & Animation',
    summary: 'Restrained delight through playback waveforms, tactile transitions, and meaningful reveal moments. Delight never blocks comprehension or adds idle noise. Equalizer bars only when audio is active. Shimmer skeletons and slide-up/scale-in used sparingly.',
    adminSections: ['Animation preview panel', 'Equalizer tester', 'Reduced-motion audit', 'Delight gallery'],
    implementationRules: [
      'Delight never blocks comprehension or adds idle noise.',
      'Use equalizer bars only when audio is active.',
      'Use shimmer skeletons and slide-up/scale-in sparingly for loading and overlay entry.',
      'Reduced motion must disable all delight animations.',
      'Reveal moments must be earned by content, not default on every element.',
    ],
    componentsRequired: ['WkEqualizer', 'WkShimmer', 'WkSlideUp', 'WkScaleIn', 'WkReveal'],
    tables: [],
    parityTargets: ['Build animation utilities with reduced-motion support.', 'Delight is restrained and content-earned.'],
    qaChecks: [
      { id: '54-no-idle', label: 'No idle noise', description: 'No idle looping animations on static surfaces.' },
      { id: '54-reduced-motion', label: 'Reduced motion', description: 'All delight animations respect prefers-reduced-motion.' },
      { id: '54-earned', label: 'Earned delight', description: 'Reveal moments are earned by content, not default.' },
    ],
  },
];