/**
 * Art Director — The ten design school definitions.
 * Each school is a complete visual DNA, not just a style shortcut.
 */

import type { DesignSchool } from './types';

export const DESIGN_SCHOOLS: Record<string, DesignSchool> = {

  swiss: {
    name: 'swiss',
    displayName: 'Swiss / International Typographic Style',
    origin: 'Zürich & Basel, Switzerland, 1950s',
    period: '1950–1975 (principles ongoing)',
    firstPrinciples: [
      'The grid is the foundation, not a guideline — decided first, everything follows',
      'Asymmetric balance over symmetric — symmetry is ornamental and anti-Swiss',
      'Sans-serif typography, typically a single family — hierarchy through scale and weight',
      'Negative space as a positive design element — composed emptiness, not empty emptiness',
      'The designer disappears — work serves the message, not the maker\'s signature',
      'Universal communication across language and culture',
    ],
    antiRules: [
      'No decoration for its own sake — borders, flourishes, ornamental initials refused',
      'No centred symmetric compositions — asymmetry is a commitment',
      'No display fonts or novelty letterforms — no script, blackletter, art-deco sans',
      'No mixed typographic families — one family, weight and size carry hierarchy',
      'No italic for emphasis — use weight or size instead',
      'No drop shadows, gradients, embossing, three-dimensional effects — flat by commitment',
    ],
    atoms: {
      compositionBias: {
        modular_grid: 'primary',
        edge_anchored: 'common',
        asymmetric: 'common',
        centered_symmetric: 'rare',
        poster_stack: 'rare',
        grid_broken: 'refused',
      },
      density: {
        balanced: 'common',
        sparse: 'common',
        dense: 'occasional',
        maximal: 'refused',
      },
      typography: {
        restrained_geometric: 'primary',
        loose_small_editorial: 'occasional',
        tight_stacked_display: 'occasional',
        mixed_weight_aggressive: 'refused',
        utility_monospace: 'rare',
      },
      color: {
        accent_only: 'primary',
        monochromatic_restraint: 'common',
        duotone_field: 'occasional',
        high_contrast_blocks: 'rare',
        soft_tonal_layers: 'refused',
      },
      imagery: {
        editorial_crop: 'common',
        duotone_image: 'common',
        no_imagery: 'common',
        full_bleed_background: 'rare',
        abstract_shapes: 'occasional',
        illustration_system: 'rare',
      },
      devices: {
        editorial_hairline: 'primary',
        column_rule: 'primary',
        negative_third: 'primary',
        letterform_motif: 'occasional',
        numeric_overlay: 'occasional',
        text_as_pattern: 'rare',
        brand_vector_corner: 'rare',
        oversized_punctuation: 'refused',
        corner_frame: 'refused',
        stamped_initials: 'refused',
      },
      motion: {
        none: 'primary',
        subtle_fade: 'occasional',
        stagger_in: 'rare',
        kinetic_type: 'refused',
        ambient_loop: 'refused',
      },
    },
    modePreference: 'either',
    signatureAccent: '#D41C14',
    secondaryAccents: ['#0A0A0A', '#E8E4DB', '#4A7FD4'],
    fontDirection: 'sans',
    textDirection: 'restrained',
    visualCharacter: 'Grid-disciplined, whitespace-composed, single-family sans-serif, black+white+one accent. The designer is invisible.',
    hybridCompat: ['editorial_magazine', 'information_design', 'bauhaus'],
  },

  modernist_poster: {
    name: 'modernist_poster',
    displayName: 'Modernist Poster',
    origin: 'Europe & international, 1920s–1970s',
    period: 'Active 1920s–present',
    firstPrinciples: [
      'The sheet is a single public argument, not a page in a system',
      'Reduction creates force — compress a subject into one remembered image',
      'Image and headline fuse into a single sign',
      'Scale is theatrical — small details support one large decision',
      'Colour is structural and memorable',
      'The poster must work at distance before it rewards close reading',
    ],
    antiRules: [
      'No sequential pacing — that belongs to editorial magazine',
      'No default corporate layout — a poster must make a claim',
      'No many equal messages — hierarchy must be ruthless',
      'No decorative illustration without conceptual force',
      'No template sameness across campaigns',
    ],
    atoms: {
      compositionBias: {
        asymmetric: 'primary',
        poster_stack: 'primary',
        edge_anchored: 'common',
        modular_grid: 'occasional',
        grid_broken: 'occasional',
        centered_symmetric: 'rare',
      },
      density: {
        balanced: 'common',
        sparse: 'common',
        dense: 'occasional',
        maximal: 'occasional',
      },
      typography: {
        tight_stacked_display: 'primary',
        restrained_geometric: 'occasional',
        loose_small_editorial: 'occasional',
        mixed_weight_aggressive: 'occasional',
        utility_monospace: 'rare',
      },
      color: {
        high_contrast_blocks: 'primary',
        duotone_field: 'common',
        accent_only: 'occasional',
        monochromatic_restraint: 'occasional',
        soft_tonal_layers: 'occasional',
      },
      imagery: {
        editorial_crop: 'primary',
        full_bleed_background: 'common',
        abstract_shapes: 'common',
        duotone_image: 'occasional',
        no_imagery: 'occasional',
        illustration_system: 'occasional',
      },
      devices: {
        numeric_overlay: 'common',
        letterform_motif: 'common',
        editorial_hairline: 'occasional',
        column_rule: 'occasional',
        oversized_punctuation: 'occasional',
        negative_third: 'occasional',
        text_as_pattern: 'occasional',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
        corner_frame: 'occasional',
      },
      motion: {
        none: 'common',
        subtle_fade: 'occasional',
        stagger_in: 'occasional',
        kinetic_type: 'occasional',
        ambient_loop: 'rare',
      },
    },
    modePreference: 'either',
    signatureAccent: '#E8302A',
    secondaryAccents: ['#1A1A1A', '#F5F2E8', '#2A5FC4'],
    fontDirection: 'sans',
    textDirection: 'expressive',
    visualCharacter: 'Bold, single-argument compositions. Theatrical scale. Colour is structural. Must work at distance.',
    hybridCompat: ['editorial_magazine', 'swiss', 'bauhaus'],
  },

  memphis_postmodern: {
    name: 'memphis_postmodern',
    displayName: 'Memphis Postmodern',
    origin: 'Milan, Italy, 1981',
    period: '1981–1988 canonical; recurring revivals',
    firstPrinciples: [
      'Good taste is not a law',
      'Geometry can be playful, decorative, and knowingly artificial',
      'Colour clashes are allowed when the clash is the point',
      'Surface pattern is content',
      'Historical quotation and parody are admissible tools',
      'Function is negotiated with theatre, not obeyed silently',
      'The composition may feel like a stage set',
      'Serious systems can be sabotaged by delight',
    ],
    antiRules: [
      'No neutral modernist purity',
      'No fear of decoration',
      'No single-family typographic obedience',
      'No muted palette as default',
      'No invisible personality',
      'No minimal product seriousness',
    ],
    atoms: {
      compositionBias: {
        grid_broken: 'common',
        centered_symmetric: 'common',
        poster_stack: 'common',
        modular_grid: 'occasional',
        edge_anchored: 'occasional',
        asymmetric: 'occasional',
      },
      density: {
        maximal: 'primary',
        dense: 'common',
        balanced: 'occasional',
        sparse: 'occasional',
      },
      typography: {
        mixed_weight_aggressive: 'primary',
        restrained_geometric: 'occasional',
        loose_small_editorial: 'occasional',
        tight_stacked_display: 'occasional',
        utility_monospace: 'occasional',
      },
      color: {
        high_contrast_blocks: 'primary',
        full_bleed_background: 'common',
        duotone_field: 'occasional',
        accent_only: 'occasional',
        soft_tonal_layers: 'occasional',
      },
      imagery: {
        abstract_shapes: 'primary',
        full_bleed_background: 'common',
        illustration_system: 'common',
        editorial_crop: 'occasional',
        duotone_image: 'occasional',
        no_imagery: 'occasional',
      },
      devices: {
        oversized_punctuation: 'primary',
        letterform_motif: 'primary',
        text_as_pattern: 'primary',
        corner_frame: 'common',
        editorial_hairline: 'occasional',
        column_rule: 'occasional',
        numeric_overlay: 'occasional',
        negative_third: 'occasional',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
      },
      motion: {
        kinetic_type: 'primary',
        ambient_loop: 'common',
        stagger_in: 'common',
        subtle_fade: 'occasional',
        none: 'occasional',
      },
    },
    modePreference: 'light',
    signatureAccent: '#FF6B35',
    secondaryAccents: ['#FFD700', '#FF1493', '#00CED1', '#7FFF00'],
    fontDirection: 'mixed',
    textDirection: 'playful',
    visualCharacter: 'Stage-set compositions. Colour clashes are the point. Pattern is content. Serious systems sabotaged by delight.',
    hybridCompat: ['bauhaus', 'editorial_magazine', 'brutalist_web'],
  },

  luxury_fashion_editorial: {
    name: 'luxury_fashion_editorial',
    displayName: 'Luxury Fashion Editorial',
    origin: 'Paris, Milan, London, New York',
    period: '20th century fashion publishing to present',
    firstPrinciples: [
      'The image is sovereign',
      'Typography behaves like couture: precise, rare, placed with control',
      'Whitespace signals price',
      'The crop can be severe, sensual, or withholding',
      'Serif display, especially Didone logic, carries luxury code',
      'The page must feel authored, not merchandised',
      'Material and body are treated as atmosphere',
    ],
    antiRules: [
      'No retail catalogue logic',
      'No too many product facts on the surface',
      'No friendly SaaS voice',
      'No cheap glamour effects',
      'No crowded discount-style CTAs',
      'No unconsidered stock photography',
    ],
    atoms: {
      compositionBias: {
        asymmetric: 'common',
        centered_symmetric: 'common',
        modular_grid: 'occasional',
        edge_anchored: 'occasional',
        poster_stack: 'occasional',
        grid_broken: 'occasional',
      },
      density: {
        sparse: 'primary',
        balanced: 'common',
        dense: 'occasional',
        maximal: 'rare',
      },
      typography: {
        loose_small_editorial: 'primary',
        restrained_geometric: 'occasional',
        tight_stacked_display: 'occasional',
        mixed_weight_aggressive: 'occasional',
        utility_monospace: 'rare',
      },
      color: {
        monochromatic_restraint: 'primary',
        soft_tonal_layers: 'primary',
        accent_only: 'common',
        duotone_field: 'common',
        high_contrast_blocks: 'occasional',
      },
      imagery: {
        editorial_crop: 'primary',
        full_bleed_background: 'primary',
        duotone_image: 'occasional',
        illustration_system: 'occasional',
        abstract_shapes: 'occasional',
        no_imagery: 'occasional',
      },
      devices: {
        negative_third: 'primary',
        editorial_hairline: 'common',
        oversized_punctuation: 'common',
        column_rule: 'occasional',
        numeric_overlay: 'occasional',
        letterform_motif: 'occasional',
        text_as_pattern: 'occasional',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
        corner_frame: 'rare',
      },
      motion: {
        subtle_fade: 'primary',
        none: 'common',
        stagger_in: 'occasional',
        kinetic_type: 'occasional',
        ambient_loop: 'occasional',
      },
    },
    modePreference: 'light',
    signatureAccent: '#C8A96E',
    secondaryAccents: ['#1A1A1A', '#F8F5EF', '#E8DDD0'],
    fontDirection: 'serif',
    textDirection: 'poetic',
    visualCharacter: 'Sovereign image. Couture typography. Whitespace signals price. Authored, never merchandised.',
    hybridCompat: ['editorial_magazine', 'japanese_minimal', 'swiss'],
  },

  japanese_minimal: {
    name: 'japanese_minimal',
    displayName: 'Japanese Minimal',
    origin: 'Japan — ma, wabi-sabi, Muji tradition',
    period: 'Continuous; contemporary discipline',
    firstPrinciples: [
      'Emptiness is not absence; it is the primary field of attention',
      'Material honesty matters more than visual novelty',
      'Hierarchy is quiet but exact',
      'Imperfection and asymmetry can humanise restraint',
      'Colour is muted, natural, or almost absent',
      'Typography is modest, precise, and lightly held',
      'The design should make the user slower, not louder',
    ],
    antiRules: [
      'No Western luxury spectacle',
      'No attention-seeking maximalism',
      'No decorative minimalism that is only empty',
      'No aggressive CTA behaviour',
      'No synthetic neon futurism',
      'No overdesigned brand marks',
    ],
    atoms: {
      compositionBias: {
        modular_grid: 'common',
        edge_anchored: 'common',
        asymmetric: 'common',
        poster_stack: 'occasional',
        grid_broken: 'occasional',
        centered_symmetric: 'occasional',
      },
      density: {
        sparse: 'primary',
        balanced: 'occasional',
        dense: 'occasional',
        maximal: 'rare',
      },
      typography: {
        restrained_geometric: 'common',
        loose_small_editorial: 'common',
        tight_stacked_display: 'occasional',
        mixed_weight_aggressive: 'rare',
        utility_monospace: 'occasional',
      },
      color: {
        monochromatic_restraint: 'primary',
        soft_tonal_layers: 'primary',
        accent_only: 'common',
        duotone_field: 'occasional',
        high_contrast_blocks: 'refused',
      },
      imagery: {
        no_imagery: 'primary',
        editorial_crop: 'common',
        full_bleed_background: 'occasional',
        duotone_image: 'occasional',
        illustration_system: 'occasional',
        abstract_shapes: 'occasional',
      },
      devices: {
        negative_third: 'primary',
        editorial_hairline: 'common',
        column_rule: 'occasional',
        numeric_overlay: 'occasional',
        oversized_punctuation: 'occasional',
        letterform_motif: 'occasional',
        text_as_pattern: 'occasional',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
        corner_frame: 'occasional',
      },
      motion: {
        none: 'primary',
        subtle_fade: 'common',
        stagger_in: 'occasional',
        kinetic_type: 'rare',
        ambient_loop: 'occasional',
      },
    },
    modePreference: 'light',
    signatureAccent: '#5C7A5C',
    secondaryAccents: ['#A89880', '#D8D0C0', '#8A9E8A'],
    fontDirection: 'mixed',
    textDirection: 'poetic',
    visualCharacter: 'Emptiness as field of attention. Muted naturals. Quiet hierarchy. Makes the reader slower.',
    hybridCompat: ['swiss', 'luxury_fashion_editorial', 'editorial_magazine'],
  },

  information_design: {
    name: 'information_design',
    displayName: 'Information Design',
    origin: 'Statistical graphics, Isotype, transit maps, civic diagrams',
    period: '19th century roots; continuously active',
    firstPrinciples: [
      'The information structure is the design',
      'Clarity is a moral commitment, not a style',
      'Hierarchy must match evidence',
      'Redundancy can help if it reduces misreading',
      'Legends, labels, axes, and annotations are first-class typography',
      'Beauty is acceptable only when it increases attention to truth',
      'The viewer should leave with a more accurate mental model',
    ],
    antiRules: [
      'No decorative chartjunk',
      'No data distortion for drama',
      'No ambiguous icons',
      'No aesthetic-first diagramming',
      'No unlabelled visual encoding',
      'No mystery as a design value',
    ],
    atoms: {
      compositionBias: {
        modular_grid: 'primary',
        edge_anchored: 'primary',
        asymmetric: 'occasional',
        poster_stack: 'occasional',
        grid_broken: 'occasional',
        centered_symmetric: 'occasional',
      },
      density: {
        dense: 'primary',
        balanced: 'common',
        sparse: 'occasional',
        maximal: 'rare',
      },
      typography: {
        restrained_geometric: 'primary',
        utility_monospace: 'primary',
        loose_small_editorial: 'occasional',
        tight_stacked_display: 'occasional',
        mixed_weight_aggressive: 'rare',
      },
      color: {
        accent_only: 'primary',
        duotone_field: 'primary',
        monochromatic_restraint: 'common',
        high_contrast_blocks: 'occasional',
        soft_tonal_layers: 'refused',
      },
      imagery: {
        illustration_system: 'primary',
        no_imagery: 'primary',
        abstract_shapes: 'common',
        editorial_crop: 'occasional',
        full_bleed_background: 'occasional',
        duotone_image: 'occasional',
      },
      devices: {
        editorial_hairline: 'primary',
        column_rule: 'primary',
        numeric_overlay: 'primary',
        text_as_pattern: 'common',
        negative_third: 'occasional',
        letterform_motif: 'occasional',
        oversized_punctuation: 'rare',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
        corner_frame: 'occasional',
      },
      motion: {
        none: 'primary',
        stagger_in: 'common',
        subtle_fade: 'occasional',
        kinetic_type: 'occasional',
        ambient_loop: 'occasional',
      },
    },
    modePreference: 'either',
    signatureAccent: '#1E7BC4',
    secondaryAccents: ['#E84040', '#2A8A3C', '#F5A623'],
    fontDirection: 'sans',
    textDirection: 'restrained',
    visualCharacter: 'Data structure IS design. Clarity is moral. Numbers are first-class typography. Dense, evidential, precise.',
    hybridCompat: ['swiss', 'editorial_magazine', 'bauhaus'],
  },

  folk_vernacular: {
    name: 'folk_vernacular',
    displayName: 'Folk Vernacular',
    origin: 'Global — sign painting, craft, textile, market, community print traditions',
    period: 'Continuous across regions; living tradition',
    firstPrinciples: [
      'Place is not decoration; it is the source',
      'The hand carries knowledge that software cannot invent',
      'Local typography, pattern, colour, and material memory are legitimate systems',
      'Irregularity can signal trust and belonging',
      'Pattern and ornament can be structural',
      'The design should feel situated, not globally neutral',
      'Borrowing without understanding becomes extraction',
    ],
    antiRules: [
      'No generic global minimalism',
      'No token cultural motifs pasted onto corporate layouts',
      'No cleaned-up heritage that erases maker energy',
      'No universalist modernist superiority',
      'No AI-invented pseudo-ethnic ornament',
      'No luxury ethnographic distance',
    ],
    atoms: {
      compositionBias: {
        asymmetric: 'primary',
        poster_stack: 'common',
        centered_symmetric: 'common',
        edge_anchored: 'occasional',
        grid_broken: 'occasional',
        modular_grid: 'rare',
      },
      density: {
        dense: 'primary',
        maximal: 'primary',
        balanced: 'common',
        sparse: 'occasional',
      },
      typography: {
        mixed_weight_aggressive: 'primary',
        restrained_geometric: 'occasional',
        loose_small_editorial: 'occasional',
        tight_stacked_display: 'occasional',
        utility_monospace: 'rare',
      },
      color: {
        high_contrast_blocks: 'primary',
        soft_tonal_layers: 'common',
        duotone_field: 'common',
        accent_only: 'occasional',
        monochromatic_restraint: 'occasional',
      },
      imagery: {
        illustration_system: 'primary',
        abstract_shapes: 'common',
        editorial_crop: 'occasional',
        full_bleed_background: 'occasional',
        duotone_image: 'occasional',
        no_imagery: 'occasional',
      },
      devices: {
        text_as_pattern: 'primary',
        stamped_initials: 'primary',
        corner_frame: 'primary',
        oversized_punctuation: 'common',
        letterform_motif: 'common',
        editorial_hairline: 'occasional',
        column_rule: 'occasional',
        numeric_overlay: 'occasional',
        negative_third: 'occasional',
        brand_vector_corner: 'occasional',
      },
      motion: {
        none: 'primary',
        ambient_loop: 'common',
        stagger_in: 'occasional',
        kinetic_type: 'occasional',
        subtle_fade: 'rare',
      },
    },
    modePreference: 'light',
    signatureAccent: '#D4832A',
    secondaryAccents: ['#2A6A4A', '#C83030', '#E8C840'],
    fontDirection: 'mixed',
    textDirection: 'expressive',
    visualCharacter: 'Situated, handmade energy. Pattern is structural. Dense, warm, irregular. Place is source.',
    hybridCompat: ['editorial_magazine', 'memphis_postmodern', 'bauhaus'],
  },

  editorial_magazine: {
    name: 'editorial_magazine',
    displayName: 'Editorial Magazine',
    origin: 'New York, London, Paris, Milan — mid-century fashion press',
    period: '1930s to present; living continuous tradition',
    firstPrinciples: [
      'The magazine is a sequence; pacing is design',
      'Image and text compose together — not wraps around',
      'Hierarchy is dramatic, not just functional',
      'Photography is primary, authored, and often full-bleed',
      'Serif typography is the default — Didone for display, Caslon for body',
      'Mixed typographic families are admitted, often required',
      'Editorial-specific devices structure the page: drop caps, pull quotes, folios',
      'The grid is structural but flexible — breaking it is legitimate for emphasis',
    ],
    antiRules: [
      'No uniform layouts across the publication',
      'No pure typography without imagery (as dominant mode)',
      'No no-hierarchy democratic layout',
      'No captions treated as afterthought',
      'No functional-over-expressive design temperament',
    ],
    atoms: {
      compositionBias: {
        asymmetric: 'primary',
        modular_grid: 'common',
        edge_anchored: 'common',
        poster_stack: 'common',
        grid_broken: 'common',
        centered_symmetric: 'occasional',
      },
      density: {
        balanced: 'primary',
        sparse: 'common',
        dense: 'common',
        maximal: 'occasional',
      },
      typography: {
        loose_small_editorial: 'primary',
        tight_stacked_display: 'common',
        mixed_weight_aggressive: 'common',
        restrained_geometric: 'common',
        utility_monospace: 'occasional',
      },
      color: {
        accent_only: 'common',
        soft_tonal_layers: 'common',
        monochromatic_restraint: 'common',
        duotone_field: 'common',
        high_contrast_blocks: 'occasional',
      },
      imagery: {
        editorial_crop: 'primary',
        full_bleed_background: 'common',
        duotone_image: 'common',
        no_imagery: 'occasional',
        illustration_system: 'occasional',
        abstract_shapes: 'occasional',
      },
      devices: {
        editorial_hairline: 'primary',
        column_rule: 'primary',
        numeric_overlay: 'primary',
        oversized_punctuation: 'common',
        letterform_motif: 'common',
        negative_third: 'common',
        text_as_pattern: 'common',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
        corner_frame: 'rare',
      },
      motion: {
        subtle_fade: 'common',
        none: 'common',
        stagger_in: 'common',
        kinetic_type: 'occasional',
        ambient_loop: 'occasional',
      },
    },
    modePreference: 'either',
    signatureAccent: '#C4883A',
    secondaryAccents: ['#1A1A14', '#F8F5EF', '#8C3030'],
    fontDirection: 'serif',
    textDirection: 'expressive',
    visualCharacter: 'Paced sequence. Authored image-text events. Dramatic typography. Mixed families. Drop caps, folios, pull quotes.',
    hybridCompat: ['swiss', 'luxury_fashion_editorial', 'modernist_poster', 'information_design'],
  },

  brutalist_web: {
    name: 'brutalist_web',
    displayName: 'Brutalist Web',
    origin: 'Web-native design reaction, mid-2010s',
    period: 'Active mid-2010s to present',
    firstPrinciples: [
      'The interface is allowed to show its structure',
      'Polish is not proof of quality',
      'Default browser elements are material, not failure',
      'Friction can be expressive when it is intentional',
      'The grid may be visible, broken, or blunt',
      'Typography can be system-like, crude, and loud',
      'The page can feel assembled rather than airbrushed',
      'Anti-beauty must still be usable enough to survive',
    ],
    antiRules: [
      'No soft SaaS smoothness',
      'No invisible interface chrome (when system is the voice)',
      'No stock illustration friendliness',
      'No over-refined gradients and glassmorphism',
      'No decoration pretending to be rebellion',
      'No accessibility-hostile chaos',
    ],
    atoms: {
      compositionBias: {
        edge_anchored: 'primary',
        grid_broken: 'primary',
        modular_grid: 'common',
        asymmetric: 'occasional',
        poster_stack: 'occasional',
        centered_symmetric: 'occasional',
      },
      density: {
        dense: 'primary',
        maximal: 'common',
        balanced: 'occasional',
        sparse: 'occasional',
      },
      typography: {
        mixed_weight_aggressive: 'primary',
        utility_monospace: 'primary',
        restrained_geometric: 'occasional',
        loose_small_editorial: 'occasional',
        tight_stacked_display: 'occasional',
      },
      color: {
        high_contrast_blocks: 'primary',
        accent_only: 'occasional',
        monochromatic_restraint: 'occasional',
        duotone_field: 'occasional',
        soft_tonal_layers: 'rare',
      },
      imagery: {
        abstract_shapes: 'common',
        no_imagery: 'common',
        editorial_crop: 'occasional',
        full_bleed_background: 'occasional',
        duotone_image: 'occasional',
        illustration_system: 'occasional',
      },
      devices: {
        text_as_pattern: 'primary',
        column_rule: 'primary',
        corner_frame: 'common',
        stagger_in: 'common',
        editorial_hairline: 'occasional',
        numeric_overlay: 'occasional',
        oversized_punctuation: 'occasional',
        letterform_motif: 'occasional',
        negative_third: 'occasional',
        stamped_initials: 'occasional',
        brand_vector_corner: 'occasional',
      },
      motion: {
        kinetic_type: 'primary',
        stagger_in: 'common',
        none: 'occasional',
        subtle_fade: 'rare',
        ambient_loop: 'occasional',
      },
    },
    modePreference: 'dark',
    signatureAccent: '#F5E642',
    secondaryAccents: ['#FF3322', '#00FF88', '#F0F0F0'],
    fontDirection: 'sans',
    textDirection: 'brutal',
    visualCharacter: 'Structure visible. Default-as-material. Friction is expressive. Crude and loud. Assembled not airbrushed.',
    hybridCompat: ['memphis_postmodern', 'bauhaus', 'information_design'],
  },

  bauhaus: {
    name: 'bauhaus',
    displayName: 'Bauhaus',
    origin: 'Weimar, Dessau, Berlin, Germany 1919–1933',
    period: '1919–1933 institutional; principles continuous',
    firstPrinciples: [
      'Art and craft are one practice — no distinction between fine art and applied craft',
      'Form follows function — but function is broadly conceived',
      'Geometric primitives are the universal vocabulary: circle, triangle, square',
      'Asymmetric composition with diagonal energy — more kinetic than Swiss',
      'Geometric sans-serif typography — ideally single-case',
      'Industrial production is the goal, not craft as nostalgia',
      'Photography is constructive, not documentary',
    ],
    antiRules: [
      'No ornament without function — decoration for its own sake refused',
      'No historicism — no quotation of classical or 19th-century styles',
      'No craft as preservation — workshops were for prototyping industrial production',
      'No mixed historical typographic families for ornamental effect',
      'No romantic/expressive illustration — geometric, constructed, deliberate only',
      'No symmetric centred composition',
    ],
    atoms: {
      compositionBias: {
        asymmetric: 'primary',
        modular_grid: 'common',
        edge_anchored: 'common',
        poster_stack: 'occasional',
        centered_symmetric: 'rare',
        grid_broken: 'rare',
      },
      density: {
        balanced: 'common',
        sparse: 'common',
        dense: 'occasional',
        maximal: 'rare',
      },
      typography: {
        restrained_geometric: 'primary',
        tight_stacked_display: 'common',
        mixed_weight_aggressive: 'occasional',
        loose_small_editorial: 'occasional',
        utility_monospace: 'rare',
      },
      color: {
        high_contrast_blocks: 'primary',
        duotone_field: 'common',
        accent_only: 'occasional',
        monochromatic_restraint: 'occasional',
        soft_tonal_layers: 'rare',
      },
      imagery: {
        abstract_shapes: 'primary',
        editorial_crop: 'common',
        duotone_image: 'common',
        illustration_system: 'occasional',
        no_imagery: 'common',
        full_bleed_background: 'occasional',
      },
      devices: {
        letterform_motif: 'primary',
        editorial_hairline: 'common',
        column_rule: 'common',
        negative_third: 'common',
        brand_vector_corner: 'occasional',
        numeric_overlay: 'occasional',
        text_as_pattern: 'occasional',
        stamped_initials: 'occasional',
        oversized_punctuation: 'rare',
        corner_frame: 'rare',
      },
      motion: {
        none: 'common',
        stagger_in: 'occasional',
        subtle_fade: 'occasional',
        kinetic_type: 'occasional',
        ambient_loop: 'rare',
      },
    },
    modePreference: 'either',
    signatureAccent: '#E83030',
    secondaryAccents: ['#2860C0', '#F5C800', '#1A1A1A'],
    fontDirection: 'sans',
    textDirection: 'restrained',
    visualCharacter: 'Geometric primitives. Primary colour blocks. Diagonal energy. Asymmetric. Constructive photography. Pedagogy made visible.',
    hybridCompat: ['swiss', 'editorial_magazine', 'memphis_postmodern', 'information_design'],
  },
};

export function getSchool(name: string): DesignSchool | null {
  return DESIGN_SCHOOLS[name] ?? null;
}

export function getAllSchools(): DesignSchool[] {
  return Object.values(DESIGN_SCHOOLS);
}

export function getCompatibleHybrids(primaryName: string): DesignSchool[] {
  const primary = getSchool(primaryName);
  if (!primary) return [];
  return primary.hybridCompat.map((n) => getSchool(n)).filter((s): s is DesignSchool => s !== null);
}

/** Pick atoms at 'primary' or 'common' level from a school */
export function getPrimaryAtoms<T extends string>(record: Record<T, 'primary' | 'common' | 'occasional' | 'rare' | 'refused'>): T[] {
  return (Object.entries(record) as [T, string][])
    .filter(([, p]) => p === 'primary' || p === 'common')
    .map(([k]) => k);
}

/** Pick the single strongest atom from a category */
export function getDefiningAtom<T extends string>(record: Record<T, 'primary' | 'common' | 'occasional' | 'rare' | 'refused'>): T {
  const primary = (Object.entries(record) as [T, string][]).find(([, p]) => p === 'primary');
  if (primary) return primary[0];
  const common = (Object.entries(record) as [T, string][]).find(([, p]) => p === 'common');
  if (common) return common[0];
  return (Object.keys(record) as T[])[0];
}