import type {
  EditorNoteMode,
  FeatureVisualMode,
  IssueArchetype,
  IssueCoverVariant,
  IssueInteractionPattern,
  IssueMood,
  IssueSignalName,
  IssueArchetypeProfile,
} from './types';

export const ISSUE_ARCHETYPE_ORDER: IssueArchetype[] = [
  'thinIssue',
  'systemsIssue',
  'fieldGuideIssue',
  'sceneIssue',
  'listeningIssue',
  'recordReviewIssue',
  'memoryIssue',
  'argumentIssue',
  'imageIssue',
  'mixedCultureIssue',
];

export const ISSUE_ARCHETYPE_PROFILES: Record<IssueArchetype, IssueArchetypeProfile> = {
  listeningIssue: {
    archetype: 'listeningIssue',
    label: 'Listening issue',
    publicName: 'the listening issue',
    signal: 'sound',
    mood: 'night',
    coverVariant: 'image-trace',
    editorNoteMode: 'song-note',
    featureVisualMode: 'photo-led',
    interactionPattern: 'listeningPath',
    readerPromise: 'Start with the sound, then follow what it opens.',
    visualPromise: 'Pulse, rhythm, related tracks, rooms and records in motion.',
    openingVerb: 'Listen first',
    pathVerb: 'Follow the sound',
    cta: 'Start with the sound',
    surfaceTone: 'warm, kinetic and music-led',
    scoreBias: 12,
    minSignalScore: 32,
  },
  sceneIssue: {
    archetype: 'sceneIssue',
    label: 'Scene issue',
    publicName: 'the scene issue',
    signal: 'scene',
    mood: 'travel',
    coverVariant: 'image-trace',
    editorNoteMode: 'letter',
    featureVisualMode: 'photo-led',
    interactionPattern: 'sceneRoute',
    readerPromise: 'Enter through the room, then follow the routes, stages and people.',
    visualPromise: 'Rooms, routes, address-like movement and cards that feel like places.',
    openingVerb: 'Enter the room',
    pathVerb: 'Follow the route',
    cta: 'Enter the room',
    surfaceTone: 'spatial, social and alive with movement',
    scoreBias: 12,
    minSignalScore: 32,
  },
  recordReviewIssue: {
    archetype: 'recordReviewIssue',
    label: 'Record issue',
    publicName: 'the record issue',
    signal: 'review',
    mood: 'paper',
    coverVariant: 'paper-cover',
    editorNoteMode: 'song-note',
    featureVisualMode: 'paper-file',
    interactionPattern: 'recordStack',
    readerPromise: 'Put the records on the table and read what they changed.',
    visualPromise: 'Stacks, sleeves, review notes, listening texture and repeat plays.',
    openingVerb: 'Put the record on',
    pathVerb: 'Read the sleeve notes',
    cta: 'Open the record stack',
    surfaceTone: 'textured, opinionated and record-led',
    scoreBias: 10,
    minSignalScore: 28,
  },
  fieldGuideIssue: {
    archetype: 'fieldGuideIssue',
    label: 'Field guide issue',
    publicName: 'the field guide issue',
    signal: 'guide',
    mood: 'travel',
    coverVariant: 'type-cover',
    editorNoteMode: 'letter',
    featureVisualMode: 'archive-board',
    interactionPattern: 'fieldGuide',
    readerPromise: 'Keep this one close. It is built for movement.',
    visualPromise: 'Routes, check-ins, what-to-notice cards and guide-like progression.',
    openingVerb: 'Carry this',
    pathVerb: 'Use the route',
    cta: 'Use the guide',
    surfaceTone: 'useful, mobile and built for action',
    scoreBias: 12,
    minSignalScore: 30,
  },
  memoryIssue: {
    archetype: 'memoryIssue',
    label: 'Memory issue',
    publicName: 'the memory issue',
    signal: 'memory',
    mood: 'paper',
    coverVariant: 'paper-cover',
    editorNoteMode: 'letter',
    featureVisualMode: 'paper-file',
    interactionPattern: 'memoryFragments',
    readerPromise: 'Move slowly. This issue is about what refuses to disappear.',
    visualPromise: 'Fragments, quote cards, quiet reveals, paper texture and names returning.',
    openingVerb: 'Follow what stays',
    pathVerb: 'Read the fragments',
    cta: 'Follow what stays',
    surfaceTone: 'quiet, intimate and unsentimental',
    scoreBias: 12,
    minSignalScore: 30,
  },
  systemsIssue: {
    archetype: 'systemsIssue',
    label: 'Systems issue',
    publicName: 'the systems issue',
    signal: 'systems',
    mood: 'signal',
    coverVariant: 'signal-grid',
    editorNoteMode: 'letter',
    featureVisualMode: 'signal-board',
    interactionPattern: 'signalBoard',
    readerPromise: 'Look under the hood. Rights, platforms, money and power sit close to the work.',
    visualPromise: 'Signal boards, receipts, claims, counters and expandable context.',
    openingVerb: 'Open the machinery',
    pathVerb: 'Follow the receipts',
    cta: 'Open the machinery',
    surfaceTone: 'sharp, forensic and systems-aware',
    scoreBias: 14,
    minSignalScore: 30,
  },
  imageIssue: {
    archetype: 'imageIssue',
    label: 'Image issue',
    publicName: 'the image issue',
    signal: 'image',
    mood: 'image',
    coverVariant: 'image-trace',
    editorNoteMode: 'image-note',
    featureVisualMode: 'photo-led',
    interactionPattern: 'imageGallery',
    readerPromise: 'Look first. Then read what the image is doing.',
    visualPromise: 'Full bleed openings, cinematic holds, gallery rhythm and sparse copy.',
    openingVerb: 'Look first',
    pathVerb: 'Follow the frame',
    cta: 'Look first',
    surfaceTone: 'visual, cinematic and restrained',
    scoreBias: 8,
    minSignalScore: 26,
  },
  argumentIssue: {
    archetype: 'argumentIssue',
    label: 'Argument issue',
    publicName: 'the argument issue',
    signal: 'argument',
    mood: 'archive',
    coverVariant: 'type-cover',
    editorNoteMode: 'letter',
    featureVisualMode: 'type-led',
    interactionPattern: 'argumentStack',
    readerPromise: 'Open the argument. These pieces do not sit politely.',
    visualPromise: 'Split panels, quote collisions, counterpoint cards and raised eyebrows.',
    openingVerb: 'Open the argument',
    pathVerb: 'Follow what talks back',
    cta: 'Open the argument',
    surfaceTone: 'sharp, critical and a little restless',
    scoreBias: 12,
    minSignalScore: 28,
  },
  mixedCultureIssue: {
    archetype: 'mixedCultureIssue',
    label: 'Mixed culture issue',
    publicName: 'the mixed issue',
    mood: 'night',
    coverVariant: 'seal-key-visual',
    editorNoteMode: 'letter',
    featureVisualMode: 'archive-board',
    interactionPattern: 'constellation',
    readerPromise: 'Start with the clearest doorway, then follow the different signals talking to each other.',
    visualPromise: 'Constellation-like paths, multiple signals and a strong editorial spine.',
    openingVerb: 'Start here',
    pathVerb: 'Follow the signals',
    cta: 'Start here',
    surfaceTone: 'wide, connective and culture-forward',
    scoreBias: 0,
    minSignalScore: 0,
  },
  thinIssue: {
    archetype: 'thinIssue',
    label: 'Thin issue',
    publicName: 'the small issue',
    mood: 'paper',
    coverVariant: 'type-cover',
    editorNoteMode: 'one-line',
    featureVisualMode: 'type-led',
    interactionPattern: 'singleThread',
    readerPromise: 'A smaller issue. No fake grand statement, just the strongest visible thread.',
    visualPromise: 'One clear path, honest copy, no overbuilt spectacle.',
    openingVerb: 'Start small',
    pathVerb: 'Follow the thread',
    cta: 'Start small',
    surfaceTone: 'short, honest and precise',
    scoreBias: 999,
    minSignalScore: 0,
  },
};

export function getIssueArchetypeProfile(archetype: IssueArchetype): IssueArchetypeProfile {
  return ISSUE_ARCHETYPE_PROFILES[archetype] ?? ISSUE_ARCHETYPE_PROFILES.mixedCultureIssue;
}

export function signalForArchetype(archetype: IssueArchetype): IssueSignalName | undefined {
  return getIssueArchetypeProfile(archetype).signal;
}

export function moodForArchetype(archetype: IssueArchetype): IssueMood {
  return getIssueArchetypeProfile(archetype).mood;
}

export function coverVariantForArchetype(archetype: IssueArchetype): IssueCoverVariant {
  return getIssueArchetypeProfile(archetype).coverVariant;
}

export function editorNoteModeForArchetype(archetype: IssueArchetype): EditorNoteMode {
  return getIssueArchetypeProfile(archetype).editorNoteMode;
}

export function featureVisualModeForArchetype(archetype: IssueArchetype): FeatureVisualMode {
  return getIssueArchetypeProfile(archetype).featureVisualMode;
}
