export type TrackLivingMemoryEditorialSeed = {
  opener: string;
  label: string;
};

const TRACK_LIVING_MEMORY_EDITORIAL_SEEDS: Record<string, TrackLivingMemoryEditorialSeed> = {
  "f810b2c1-7018-4412-9404-e8685b22062e": { opener: "Track one is a statement of intent. If VILE NAPENDA reached you before the rest of the album did, tell us where, and what was happening around you.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "c82d10bd-8b55-4e87-970d-d9e5bb40c553": { opener: "Three artists on one track usually means there is a story about how they ended up in the same room. If you know it, or PLUMBER became a thing wherever you are, this page is listening.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "419bb7ea-8fe4-4bba-9855-a99ab44ef894": { opener: "Some songs pick their audience right in the title. Who played it, where, and what happened next? Somebody remembers.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "0c65f976-5356-4af1-8a79-e6704c24868b": { opener: "The malosh feature raises a question the credits do not answer: how did this pairing happen? And a better one: what does this song do in a full room?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "adeb71dc-178a-47bc-aef2-b5451a68fdcb": { opener: "Zawadi means a gift. If this one was handed to you by a friend, a DJ, or an algorithm on a good day, tell us what came with it.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "e7b5e5cd-4d0c-4841-b187-2ae55800f1cf": { opener: "Is Betty a real person? The record does not say. If you know, or the song simply knows you, this is the place to say so.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "1429a3ce-59e7-44cb-a573-79cdd1b41849": { opener: "A name, a song, and no story on record to connect them. Someone out there can. We would be grateful.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "8f7a9dfd-cef1-42a8-92af-6ab5676a7f78": { opener: "A curious title with no explanation on file. If you know what it means or where it comes from, the record needs you.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "182fe408-53a3-4c54-a111-5f868eae88c4": { opener: "The oldest word in East African songwriting, and it never wears out. What does Winyo's version hold for you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "86245b6a-be33-448c-94af-38302766f2b6": { opener: "The record holds a title and little else. If you know the language, the story, or the room this was made in, please add what you know.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "685b5de2-d681-44b6-87bd-61ec6fd243a8": { opener: "Intros are chosen with care and explained almost never. Why this door into the album? If you know, or it stops you every time, say so.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "5f1d6357-4e63-4f1e-ba1e-16f318e0ed82": { opener: "The album takes its name from this song, which usually means it carries the heart of the whole project. What do the words mean, and what do they mean to you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "da3c0b84-cd6d-4686-91bb-489fb447dd9f": { opener: "A name shared by a thousand songs, yet every Maria is someone specific. If you can hear what this one is doing, tell us.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "42783c0d-e2ce-4814-ad4e-1fa6b2473beb": { opener: "A title most visitors to this page cannot translate. If you can, you are exactly who this page is waiting for.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "7c488f46-2e25-49b3-9f0f-23f49d5ea456": { opener: "Short title, long tradition behind it. If you know what Jowo carries, or the song carries you, leave that here.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "8e6ddac6-92b1-4ebc-b7ec-1e4050fc170b": { opener: "The tracklist tells you whose song this is. It does not tell you what Sewersydaa was working through, or what it does for the people who run it back. If you know either, speak.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "8891dfac-a8cc-403f-96d2-80169c67ee5a": { opener: "A title like a detonation. What does it reference, and where did it land hardest? Somebody in Eastlands probably knows.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "0adc366f-e2ea-434a-807d-06738dc21c20": { opener: "A song named for home. If you are from Eastlands, this track is partly about you, and your version of it belongs here.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "e505c9a2-d060-4863-b180-21b5ce8c2ede": { opener: "Two guests, one Sewersydaa cut, and no record of how it came together. Who knows the session story? Who carried the song after?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "0f3f504b-c673-411b-afbc-a9627b322d1d": { opener: "Even the spelling is a story nobody has told yet. If you know what Ki Di'ng means or where it started, the record is listening.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "a524cada-0038-4c56-925e-c429aceca096": { opener: "Ukweli and Xenia have a working shorthand the credits cannot show. If you heard Options and felt the conversation inside it, or you know how it was made, add your piece.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "f3dab786-04d6-4e70-a688-cda37bce2016": { opener: "A title pointing in two directions at once. Where did it catch you, and which direction were you facing?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "df002f69-d64d-4497-9428-6f1ce10666e0": { opener: "Some songs are named for exactly what they do. What was happening in your life when this one arrived?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "52b12791-709e-4470-a11e-f466783df685": { opener: "Songs about returning always seem to find people mid-return. If this one found you that way, that story is worth keeping.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "0cd402ad-35b9-413e-a187-e1799e55f06b": { opener: "Rudia: repeat, come back, do it again. Tell us honestly, how many times, and why?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "1d9606ce-a689-4c4e-af56-7681a179dcd6": { opener: "The title track brings in Bien, and somewhere there is a story about that phone call. There is also yours: where were you when you first heard it?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "d5a2598f-e39a-4ebc-b7fa-6e35f23774ae": { opener: "The title says it is acceptable. What it became in cars, rooms and functions is for you to tell us.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "fbe0a4c9-0775-4ce7-aad5-3c307dc2412d": { opener: "All caps and no explanation on file. If you know the story, or the song owns a specific memory of yours, put it here.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "f37310d2-7f97-4289-bb31-b8a6cc97493e": { opener: "A remix means the original already lived a life. Which version reached you first, and what changed when Sofiya Nzau came in?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "58af8212-8b39-48d7-9ebe-0cb0d3b6d340": { opener: "Coster Ojwang walks into a Matata record and something new happens. If you were paying attention when this dropped, tell us what you noticed.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "8f61381b-5d87-478d-ad26-0013145b0331": { opener: "Opening an EP called Needs with No Love is a choice. What do you think they meant, and what did it mean to you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "e8c99cb4-f5dc-4196-aa1c-3455c5b5eb10": { opener: "Some songs are for moving. Where has Sway moved you, literally or otherwise?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "4d0be9ae-6e4a-497c-9f48-c5913a34a726": { opener: "One word, whole situation. If this song read your messages, this page is a safe place to admit it.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "59bc9d05-8e7a-41da-8e5e-5bd5fa9bf2d5": { opener: "Do not disturb, except Zaituni Wambui got through. How did this collaboration happen, and who was it made for? Someone knows.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "b2fb6642-cc39-44ea-9f91-561cc0a24a2e": { opener: "EPs end on Forever for a reason. What does this closer leave you with?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "6ccfacab-1a38-46bc-9494-c8016bf18f35": { opener: "Skin like the sun. A line like that comes from somewhere real. If you know where, or it landed on you like it was written for you, tell us.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "d7370b5c-1d64-4a98-85d0-f35d4f9dbd90": { opener: "It is you. Every listener quietly fills in their own you. Who was yours?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "75083467-11cb-4a2e-a35e-0fe3a5fbbde9": { opener: "An R&B album with a track called Mbuzi deserves an explanation, and we do not have one yet. Help.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "1a16ce1c-8d51-472b-b434-db838a8a286a": { opener: "Songs called Sober are rarely only about drinking. What is this one about, from where you are standing?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "e78eb49c-0667-44f4-b063-2b58a789628d": { opener: "Two voices choosing. If this song entered a wedding, a playlist, or an apology near you, the record wants to know.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "f4579864-d636-43f2-84d4-ff891166d6ec": { opener: "A date for a title means something happened. Maya knows what. Do you? And what does October 16th mean in your own calendar?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "f678a1df-97e3-4c58-9b26-7db027feb04d": { opener: "Almost the title track, with Ywaya Tajiri along. If you know how that pairing came about, or this song marks a sweet time of yours, both belong here.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "7db9d350-c5c0-4443-8c9f-0a3d9e2ba6dd": { opener: "Hold on, stretched into a new word. What were you holding onto when it found you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "7c916b0a-1ea1-4869-b3bc-f178d84b6694": { opener: "Everyone has looked the other way at least once. This song knows it. What is your version?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "b7828900-aab2-483f-8a38-11d443544f58": { opener: "Simple title, and simple titles usually hide the best stories. What do you know about this one, or what does it know about you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "5a25bbb9-49db-4868-985c-1f18aeaa58ac": { opener: "Opening an album with Legendary is either confidence or a dare. Where were you when you pressed play on track one, day one?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "caad0c22-fea7-45b9-8d5e-6775ec038054": { opener: "Some titles are advice. If this one entered your vocabulary, or your speakers on repeat, tell us how.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "afab95e3-a514-4724-9f71-3c3de34ac578": { opener: "Gratitude from an artist who went quiet and came back. What do you hear in it, and what were you grateful for when it arrived?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "3ba0cf29-fac5-4c6f-ad70-5bd0a9ec75a0": { opener: "A city as a title always carries a story. Whose Dubai is this one, and where did the song play loudest for you?", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
  "de6877e3-8aab-4a62-8a67-7b957e7d3b46": { opener: "Nyashinski has always been precise with words. Why this one? If this song scored a sharp-dressed moment of yours, the page is open.", label: "Editorial. Written by WAKILISHA to open this page. The memories below belong to the people who lived them." },
};

export function getTrackLivingMemoryEditorialSeed(entityId?: string | null): TrackLivingMemoryEditorialSeed | null {
  const key = entityId?.trim() || "";
  return key ? TRACK_LIVING_MEMORY_EDITORIAL_SEEDS[key] || null : null;
}
