import type {
  ChartFamily,
  IngestJob,
  IngestSource,
  RawSourceItem,
  IngestCandidate,
  IngestMatch,
  ReviewIssue,
  DraftEntry,
  IngestJobLog,
  ChartEdition,
  Snapshot,
  DashboardKpis,
  IngestJobStatus,
  SourceType,
  Provider,
  DiscoveredCsvSource,
  CsvRowProvenance,
} from "./types";

export const DEMO_JOB_ID = "demo-job-001";

export const mockChartFamilies: ChartFamily[] = [
  {
    id: "fam-001",
    familyKey: "wakilisha_top_40",
    label: "WAKILISHA Top 40",
    description: "The definitive weekly chart of the most streamed African tracks across all platforms.",
    defaultChartSize: 40,
    defaultRegion: "Africa",
    editionFrequency: "weekly",
    defaultRuleset: "standard_weekly",
    defaultScoringModel: "weighted_multi_source_v1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2026-05-20T14:30:00Z",
  },
  {
    id: "fam-002",
    familyKey: "wakilisha_top_100",
    label: "WAKILISHA Top 100",
    description: "The extended weekly chart capturing the full breadth of African music consumption.",
    defaultChartSize: 100,
    defaultRegion: "Africa",
    editionFrequency: "weekly",
    defaultRuleset: "standard_weekly",
    defaultScoringModel: "weighted_multi_source_v1",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2026-05-20T14:30:00Z",
  },
  {
    id: "fam-003",
    familyKey: "wakilisha_afrobeats_20",
    label: "Afrobeats Top 20",
    description: "Weekly Afrobeats-specific chart focused on the genre's global reach.",
    defaultChartSize: 20,
    defaultRegion: "Africa",
    editionFrequency: "weekly",
    defaultRuleset: "genre_specific",
    defaultScoringModel: "weighted_multi_source_v1",
    createdAt: "2025-03-10T10:00:00Z",
    updatedAt: "2026-05-20T14:30:00Z",
  },
];

export const mockIngestJobs: IngestJob[] = [
  {
    id: DEMO_JOB_ID,
    chartFamilyId: "fam-001",
    editionId: "ed-2026-w22",
    editionSlug: "2026-week-22",
    status: "review" as IngestJobStatus,
    editionDate: "2026-05-30",
    periodStart: "2026-05-23",
    periodEnd: "2026-05-30",
    chartSize: 40,
    rulesetKey: "standard_weekly",
    scoringModelKey: "weighted_multi_source_v1",
    createdBy: "James",
    createdAt: "2026-05-30T10:02:00Z",
    updatedAt: "2026-05-30T11:45:00Z",
    completedAt: null,
    sourceSummary: {
      totalSources: 4,
      completedSources: 4,
      failedSources: 0,
      totalRawItems: 412,
      totalNormalized: 396,
    },
    jobSummary: {
      totalCandidates: 396,
      approvedMatches: 342,
      unresolvedMatches: 31,
      newEntities: 23,
      highIssues: 2,
      mediumIssues: 7,
      lowIssues: 14,
      eligibleCandidates: 382,
      excludedCandidates: 14,
      finalChartSize: 40,
    },
    errorMessage: null,
  },
  {
    id: "job-002",
    chartFamilyId: "fam-002",
    editionId: "ed-2026-w22",
    editionSlug: "2026-week-22",
    status: "published",
    editionDate: "2026-05-30",
    periodStart: "2026-05-23",
    periodEnd: "2026-05-30",
    chartSize: 100,
    rulesetKey: "standard_weekly",
    scoringModelKey: "weighted_multi_source_v1",
    createdBy: "Sarah",
    createdAt: "2026-05-30T09:00:00Z",
    updatedAt: "2026-05-30T12:30:00Z",
    completedAt: "2026-05-30T12:30:00Z",
    sourceSummary: {
      totalSources: 3,
      completedSources: 3,
      failedSources: 0,
      totalRawItems: 892,
      totalNormalized: 847,
    },
    jobSummary: {
      totalCandidates: 847,
      approvedMatches: 781,
      unresolvedMatches: 0,
      newEntities: 66,
      highIssues: 0,
      mediumIssues: 3,
      lowIssues: 8,
      eligibleCandidates: 834,
      excludedCandidates: 13,
      finalChartSize: 100,
    },
    errorMessage: null,
  },
  {
    id: "job-003",
    chartFamilyId: "fam-003",
    editionId: "ed-2026-w22",
    editionSlug: "2026-week-22",
    status: "failed",
    editionDate: "2026-05-30",
    periodStart: "2026-05-23",
    periodEnd: "2026-05-30",
    chartSize: 20,
    rulesetKey: "genre_specific",
    scoringModelKey: "weighted_multi_source_v1",
    createdBy: "Michael",
    createdAt: "2026-05-30T08:30:00Z",
    updatedAt: "2026-05-30T08:45:00Z",
    completedAt: null,
    sourceSummary: {
      totalSources: 2,
      completedSources: 1,
      failedSources: 1,
      totalRawItems: 156,
      totalNormalized: 0,
    },
    jobSummary: {
      totalCandidates: 0,
      approvedMatches: 0,
      unresolvedMatches: 0,
      newEntities: 0,
      highIssues: 0,
      mediumIssues: 0,
      lowIssues: 0,
      eligibleCandidates: 0,
      excludedCandidates: 0,
      finalChartSize: 0,
    },
    errorMessage: "Spotify API rate limit exceeded during source fetch",
  },
  {
    id: "job-004",
    chartFamilyId: "fam-001",
    editionId: "ed-2026-w21",
    editionSlug: "2026-week-21",
    status: "published",
    editionDate: "2026-05-23",
    periodStart: "2026-05-16",
    periodEnd: "2026-05-23",
    chartSize: 40,
    rulesetKey: "standard_weekly",
    scoringModelKey: "weighted_multi_source_v1",
    createdBy: "James",
    createdAt: "2026-05-23T10:00:00Z",
    updatedAt: "2026-05-23T12:15:00Z",
    completedAt: "2026-05-23T12:15:00Z",
    sourceSummary: {
      totalSources: 4,
      completedSources: 4,
      failedSources: 0,
      totalRawItems: 398,
      totalNormalized: 387,
    },
    jobSummary: {
      totalCandidates: 387,
      approvedMatches: 356,
      unresolvedMatches: 0,
      newEntities: 31,
      highIssues: 0,
      mediumIssues: 5,
      lowIssues: 11,
      eligibleCandidates: 376,
      excludedCandidates: 11,
      finalChartSize: 40,
    },
    errorMessage: null,
  },
  {
    id: "job-005",
    chartFamilyId: "fam-001",
    editionId: null,
    editionSlug: null,
    status: "draft",
    editionDate: "2026-06-06",
    periodStart: "2026-05-30",
    periodEnd: "2026-06-06",
    chartSize: 40,
    rulesetKey: "standard_weekly",
    scoringModelKey: "weighted_multi_source_v1",
    createdBy: "James",
    createdAt: "2026-05-31T09:00:00Z",
    updatedAt: "2026-05-31T09:00:00Z",
    completedAt: null,
    sourceSummary: {
      totalSources: 0,
      completedSources: 0,
      failedSources: 0,
      totalRawItems: 0,
      totalNormalized: 0,
    },
    jobSummary: {
      totalCandidates: 0,
      approvedMatches: 0,
      unresolvedMatches: 0,
      newEntities: 0,
      highIssues: 0,
      mediumIssues: 0,
      lowIssues: 0,
      eligibleCandidates: 0,
      excludedCandidates: 0,
      finalChartSize: 0,
    },
    errorMessage: null,
  },
];

export const mockSources: IngestSource[] = [
  {
    id: "src-001",
    jobId: DEMO_JOB_ID,
    sourceType: "spotify" as SourceType,
    provider: "spotify" as Provider,
    sourceUrl: "https://open.spotify.com/playlist/37i9dQZF1DXc2aWXf7eND5",
    uploadedFileId: null,
    weight: 0.4,
    priority: 1,
    status: "completed",
    rawCount: 100,
    normalizedCount: 100,
    errorCount: 0,
    fetchedAt: "2026-05-30T10:04:00Z",
    rawResponseHash: "a1b2c3d4e5f6",
    errorMessage: null,
  },
  {
    id: "src-002",
    jobId: DEMO_JOB_ID,
    sourceType: "apple_music" as SourceType,
    provider: "apple" as Provider,
    sourceUrl: "https://music.apple.com/ug/playlist/afrobeats-2026/pl.123456789",
    uploadedFileId: null,
    weight: 0.3,
    priority: 2,
    status: "completed",
    rawCount: 150,
    normalizedCount: 146,
    errorCount: 4,
    fetchedAt: "2026-05-30T10:05:00Z",
    rawResponseHash: "b2c3d4e5f6g7",
    errorMessage: null,
  },
  {
    id: "src-003",
    jobId: DEMO_JOB_ID,
    sourceType: "youtube" as SourceType,
    provider: "youtube" as Provider,
    sourceUrl: "https://youtube.com/playlist?list=PLabcdefghij",
    uploadedFileId: null,
    weight: 0.2,
    priority: 3,
    status: "completed",
    rawCount: 80,
    normalizedCount: 78,
    errorCount: 2,
    fetchedAt: "2026-05-30T10:06:00Z",
    rawResponseHash: "c3d4e5f6g7h8",
    errorMessage: null,
  },
  {
    id: "src-004",
    jobId: DEMO_JOB_ID,
    sourceType: "csv" as SourceType,
    provider: "csv" as Provider,
    sourceUrl: null,
    uploadedFileId: "file-001",
    weight: 0.1,
    priority: 4,
    status: "completed",
    rawCount: 82,
    normalizedCount: 72,
    errorCount: 10,
    fetchedAt: "2026-05-30T10:07:00Z",
    rawResponseHash: "d4e5f6g7h8i9",
    errorMessage: null,
  },
];

export const mockRawItems: RawSourceItem[] = [
  {
    id: "raw-001",
    jobId: DEMO_JOB_ID,
    sourceId: "src-001",
    sourcePosition: 1,
    providerTrackId: "spotify:track:4iV5W9uYEdYUVa79Axb7Rh",
    providerArtistId: "spotify:artist:0TnOYISbd1XYRBk9myaseg",
    isrc: "USUM72012345",
    titleRaw: "Ojuelegba",
    artistRaw: "WizKid",
    releaseRaw: "Ayo",
    rawPayloadJson: { popularity: 92, streams: 4500000 },
    rawHash: "hash001",
    createdAt: "2026-05-30T10:04:00Z",
  },
  {
    id: "raw-002",
    jobId: DEMO_JOB_ID,
    sourceId: "src-001",
    sourcePosition: 2,
    providerTrackId: "spotify:track:6gKgy9d8Un0adUa71b4Ot8",
    providerArtistId: "spotify:artist:3tVQd5CTwcnwm2DD8",
    isrc: "USUM72012346",
    titleRaw: "Last Last",
    artistRaw: "Burna Boy",
    releaseRaw: "Love, Damini",
    rawPayloadJson: { popularity: 91, streams: 4200000 },
    rawHash: "hash002",
    createdAt: "2026-05-30T10:04:00Z",
  },
  {
    id: "raw-003",
    jobId: DEMO_JOB_ID,
    sourceId: "src-002",
    sourcePosition: 1,
    providerTrackId: "apple:track:1234567890",
    providerArtistId: "apple:artist:9876543210",
    isrc: "USUM72012345",
    titleRaw: "Ojuelegba",
    artistRaw: "WizKid",
    releaseRaw: "Ayo",
    rawPayloadJson: { position: 1, plays: 3800000 },
    rawHash: "hash003",
    createdAt: "2026-05-30T10:05:00Z",
  },
];

const candidateArtworks = [
  "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=200&h=200&fit=crop",
];

const candidateTitles = [
  "Ojuelegba",
  "Last Last",
  "Essence",
  "Rush",
  "Calm Down",
  "Sability",
  "Buga",
  "Gwagwalada",
  "Asake",
  "Yoga",
  "Terminator",
  "Soweto",
  "People",
  "Bandana",
  "Loaded",
  "Who Is Your Guy",
  "Kolomental",
  "Cough",
  "Palazzo",
  "Tatata",
  "Soso",
  "Organize",
  "Peace Be Unto You",
  "Free Mind",
  "Overloading",
  "Bounce",
  "Woman",
  "Peru",
  "Bloody Samaritan",
  "Understanding",
  "For My Hand",
  "Dada",
  "Ameno Amapiano",
  "Monalisa",
  "Love Nwantiti",
  "Bad Influence",
  "KPK",
  "Bounce",
  "Finesse",
  "Sungba",
  "Ku Lo Sa",
];

const candidateArtists = [
  "WizKid", "Burna Boy", "Tems", "Ayra Starr", "Rema",
  "Yemi Alade", "Kizz Daniel", "Johnny Drille", "Teni", "Bnxn",
  "King Promise", "Libianca", "Joeboy", "Fireboy DML", "Asake",
  "Camidoh", "Oxlade", "Omah Lay", "Ruger", "DJ Spinall",
  "Niniola", "Seyi Vibez", "Mohbad", "Zinoleesky", "Victony",
  "Simi", "Patoranking", "Diamond Platnumz", "Davido", "Tiwa Savage",
  "CKay", "Lojay", "Ladipoe", "Yemi Alade", "Sauti Sol",
  "Mr Eazi", "Maleek Berry", "Nonso Amadi", "Koffee", "Sho Madjozi",
];

export const mockCandidates: IngestCandidate[] = Array.from({ length: 40 }, (_, i) => {
  const isrc = `USUM72012${(300 + i).toString().padStart(3, "0")}`;
  const hasUnresolved = i === 5 || i === 18;
  const isNewEntity = i === 37 || i === 38;
  const isExcluded = i === 39;
  const score = Math.round(95 - i * 1.8 + Math.random() * 5);
  return {
    id: `cand-${(i + 1).toString().padStart(3, "0")}`,
    jobId: DEMO_JOB_ID,
    rawItemIds: [`raw-${(i + 1).toString().padStart(3, "0")}`],
    normalizedTitle: candidateTitles[i % candidateTitles.length],
    normalizedArtistLine: candidateArtists[i % candidateArtists.length],
    normalizedArtists: [candidateArtists[i % candidateArtists.length]],
    normalizedReleaseTitle: `${candidateTitles[i % candidateTitles.length]} (Single)`,
    isrc,
    upc: null,
    artworkUrl: candidateArtworks[i % candidateArtworks.length],
    previewUrl: null,
    externalUrls: {
      spotify: `https://open.spotify.com/track/${isrc}`,
    },
    durationMs: 180000 + Math.random() * 120000,
    releaseDate: "2026-04-15",
    label: ["Starboy Entertainment", "Atlantic Records", "Mavin Records", "YBNL Nation", "Marlian Music"][i % 5],
    genre: "Afrobeats",
    sourcePositions: {
      spotify: Math.max(1, i + Math.floor(Math.random() * 5)),
      apple: Math.max(1, i + Math.floor(Math.random() * 3)),
      youtube: Math.max(1, i + Math.floor(Math.random() * 7)),
    },
    sourceMetrics: {
      spotify: Math.round(4500000 - i * 80000),
      apple: Math.round(3800000 - i * 70000),
      youtube: Math.round(2100000 - i * 40000),
      airplay: Math.round(150000 - i * 3000),
    },
    candidateHash: `hash-${i + 1}`,
    dedupeGroupKey: null,
    eligibilityStatus: isExcluded ? "excluded" : "eligible",
    eligibilityReasons: isExcluded ? ["Track older than 6 months on non-recurrent chart"] : [],
    score,
    calculatedRank: i + 1,
    manualRankOverride: null,
    finalRank: i + 1,
    status: isExcluded
      ? "excluded"
      : hasUnresolved
        ? "needs_review"
        : isNewEntity
          ? "approved"
          : "approved",
    createdAt: "2026-05-30T10:05:00Z",
    updatedAt: "2026-05-30T10:05:00Z",
  };
});

export const mockMatches: IngestMatch[] = mockCandidates.map((c, i) => {
  const hasUnresolved = i === 5 || i === 18;
  const isNewEntity = i === 37 || i === 38;
  return {
    id: `match-${c.id}`,
    jobId: DEMO_JOB_ID,
    candidateId: c.id,
    canonicalTrackId: isNewEntity ? null : `track-${i + 1}`,
    canonicalReleaseId: isNewEntity ? null : `release-${i + 1}`,
    canonicalArtistIds: isNewEntity ? [] : [`artist-${i + 1}`],
    matchConfidence: isNewEntity ? 0 : hasUnresolved ? 62 : 95,
    matchMethod: isNewEntity ? "new_entity" : hasUnresolved ? "title_artist" : "isrc",
    matchNotes: isNewEntity
      ? "New track not found in canonical registry"
      : hasUnresolved
        ? "Fuzzy match on title + artist — needs confirmation"
        : "ISRC exact match",
    approvedBy: isNewEntity ? null : hasUnresolved ? null : "James",
    approvedAt: isNewEntity ? null : hasUnresolved ? null : "2026-05-30T10:20:00Z",
  };
});

export const mockReviewIssues: ReviewIssue[] = [
  {
    id: "issue-001",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-006",
    severity: "high",
    issueType: "unresolved_canonical_track",
    message: "Candidate 'Yoga' matched with low confidence (62%) to canonical track. ISRC not available. Needs manual review.",
    status: "open",
    blocking: true,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:30:00Z",
  },
  {
    id: "issue-002",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-019",
    severity: "high",
    issueType: "unresolved_canonical_track",
    message: "Candidate 'Terminator' has conflicting provider metadata. Spotify shows 'King Promise' but Apple Music shows 'King Promise ft. Olivetheboy'. Artist split needs resolution.",
    status: "open",
    blocking: true,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:31:00Z",
  },
  {
    id: "issue-003",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-001",
    severity: "medium",
    issueType: "missing_preview",
    message: "Candidate 'Ojuelegba' has no preview URL available from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:32:00Z",
  },
  {
    id: "issue-004",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-002",
    severity: "medium",
    issueType: "missing_preview",
    message: "Candidate 'Last Last' has no preview URL available from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:32:00Z",
  },
  {
    id: "issue-005",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-003",
    severity: "medium",
    issueType: "missing_artwork",
    message: "Candidate 'Essence' artwork is low resolution (below 300x300). Consider updating from canonical source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:33:00Z",
  },
  {
    id: "issue-006",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-001",
    severity: "medium",
    issueType: "suspicious_new_number_one",
    message: "Candidate 'Ojuelegba' jumped from rank #3 to #1. Verify no streaming manipulation.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:34:00Z",
  },
  {
    id: "issue-007",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-010",
    severity: "medium",
    issueType: "huge_movement_jump",
    message: "Candidate 'Buga' moved from #28 to #10 (+18 positions). Unusual jump — verify data integrity.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:35:00Z",
  },
  {
    id: "issue-008",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-011",
    severity: "medium",
    issueType: "missing_source_url",
    message: "Candidate 'Gwagwalada' missing YouTube source URL despite appearing in YouTube chart.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:36:00Z",
  },
  {
    id: "issue-009",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-020",
    severity: "medium",
    issueType: "provider_metadata_conflict",
    message: "Candidate 'Tatata' has duration mismatch: Spotify 3:42 vs Apple Music 3:38. 4 second difference.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:37:00Z",
  },
  {
    id: "issue-010",
    jobId: DEMO_JOB_ID,
    candidateId: null,
    severity: "low",
    issueType: "missing_title",
    message: "2 raw items from CSV source have empty title fields. Skipped during normalization.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:38:00Z",
  },
  {
    id: "issue-011",
    jobId: DEMO_JOB_ID,
    candidateId: null,
    severity: "low",
    issueType: "missing_artist",
    message: "3 raw items from CSV source have empty artist fields. Skipped during normalization.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:38:00Z",
  },
  {
    id: "issue-012",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-025",
    severity: "low",
    issueType: "missing_artwork",
    message: "Candidate 'Overloading' has no artwork URL from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:39:00Z",
  },
  {
    id: "issue-013",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-030",
    severity: "low",
    issueType: "missing_artwork",
    message: "Candidate 'Bloody Samaritan' has no artwork URL from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:39:00Z",
  },
  {
    id: "issue-014",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-035",
    severity: "low",
    issueType: "missing_artwork",
    message: "Candidate 'Ameno Amapiano' has no artwork URL from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:39:00Z",
  },
  {
    id: "issue-015",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-040",
    severity: "low",
    issueType: "missing_artwork",
    message: "Candidate 'Sungba' has no artwork URL from any source.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:39:00Z",
  },
  {
    id: "issue-016",
    jobId: DEMO_JOB_ID,
    candidateId: null,
    severity: "low",
    issueType: "missing_source_url",
    message: "5 candidates are missing Apple Music source URLs. This is within normal range for non-Apple territories.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:40:00Z",
  },
  {
    id: "issue-017",
    jobId: DEMO_JOB_ID,
    candidateId: "cand-007",
    severity: "low",
    issueType: "provider_metadata_conflict",
    message: "Candidate 'Sability' has release date mismatch: Spotify 2026-03-15 vs Apple Music 2026-03-18.",
    status: "open",
    blocking: false,
    resolutionNote: null,
    resolvedBy: null,
    resolvedAt: null,
    createdAt: "2026-05-30T10:41:00Z",
  },
];

export const mockDraftEntries: DraftEntry[] = mockCandidates
  .filter((c) => c.status !== "excluded")
  .slice(0, 40)
  .map((c, i) => ({
    id: `draft-${c.id}`,
    jobId: DEMO_JOB_ID,
    candidateId: c.id,
    finalRank: i + 1,
    canonicalTrackId: c.id,
    movement: i < 3 ? "up" : i > 35 ? "new" : "same",
    previousRank: i < 3 ? i + 3 : null,
    peakPosition: i + 1,
    weeksOnChart: i < 10 ? 5 + i : 2,
    score: c.score,
    entryPayload: { track: c },
    locked: false,
  }));

export const mockLogs: IngestJobLog[] = [
  {
    id: "log-001",
    jobId: DEMO_JOB_ID,
    stage: "job_created",
    level: "info",
    message: "Job created by James",
    contextJson: {},
    createdBy: "James",
    createdAt: "2026-05-30T10:02:00Z",
  },
  {
    id: "log-002",
    jobId: DEMO_JOB_ID,
    stage: "source_added",
    level: "info",
    message: "Spotify source added",
    contextJson: { sourceUrl: "https://open.spotify.com/playlist/..." },
    createdBy: "James",
    createdAt: "2026-05-30T10:03:00Z",
  },
  {
    id: "log-003",
    jobId: DEMO_JOB_ID,
    stage: "source_added",
    level: "info",
    message: "Apple Music source added",
    contextJson: {},
    createdBy: "James",
    createdAt: "2026-05-30T10:03:00Z",
  },
  {
    id: "log-004",
    jobId: DEMO_JOB_ID,
    stage: "source_added",
    level: "info",
    message: "YouTube source added",
    contextJson: {},
    createdBy: "James",
    createdAt: "2026-05-30T10:03:00Z",
  },
  {
    id: "log-005",
    jobId: DEMO_JOB_ID,
    stage: "source_added",
    level: "info",
    message: "CSV source added",
    contextJson: {},
    createdBy: "James",
    createdAt: "2026-05-30T10:03:00Z",
  },
  {
    id: "log-006",
    jobId: DEMO_JOB_ID,
    stage: "fetch_sources",
    level: "info",
    message: "Spotify fetch started",
    contextJson: {},
    createdBy: "system",
    createdAt: "2026-05-30T10:04:00Z",
  },
  {
    id: "log-007",
    jobId: DEMO_JOB_ID,
    stage: "fetch_sources",
    level: "info",
    message: "Spotify fetch completed: 100 rows",
    contextJson: { rawCount: 100 },
    createdBy: "system",
    createdAt: "2026-05-30T10:04:00Z",
  },
  {
    id: "log-008",
    jobId: DEMO_JOB_ID,
    stage: "fetch_sources",
    level: "info",
    message: "Apple Music fetch completed: 150 rows",
    contextJson: { rawCount: 150 },
    createdBy: "system",
    createdAt: "2026-05-30T10:05:00Z",
  },
  {
    id: "log-009",
    jobId: DEMO_JOB_ID,
    stage: "fetch_sources",
    level: "info",
    message: "YouTube fetch completed: 80 rows",
    contextJson: { rawCount: 80 },
    createdBy: "system",
    createdAt: "2026-05-30T10:06:00Z",
  },
  {
    id: "log-010",
    jobId: DEMO_JOB_ID,
    stage: "fetch_sources",
    level: "info",
    message: "CSV parse completed: 82 rows",
    contextJson: { rawCount: 82 },
    createdBy: "system",
    createdAt: "2026-05-30T10:07:00Z",
  },
  {
    id: "log-011",
    jobId: DEMO_JOB_ID,
    stage: "normalize",
    level: "info",
    message: "Normalization completed: 396 candidates",
    contextJson: { candidateCount: 396 },
    createdBy: "system",
    createdAt: "2026-05-30T10:05:00Z",
  },
  {
    id: "log-012",
    jobId: DEMO_JOB_ID,
    stage: "dedupe",
    level: "info",
    message: "4 duplicates removed",
    contextJson: { removedCount: 4 },
    createdBy: "system",
    createdAt: "2026-05-30T10:06:00Z",
  },
  {
    id: "log-013",
    jobId: DEMO_JOB_ID,
    stage: "matching",
    level: "info",
    message: "Matching completed: 342 auto, 9 needs review, 6 new",
    contextJson: { auto: 342, needsReview: 9, new: 6 },
    createdBy: "system",
    createdAt: "2026-05-30T10:06:00Z",
  },
  {
    id: "log-014",
    jobId: DEMO_JOB_ID,
    stage: "eligibility",
    level: "info",
    message: "Eligibility evaluation complete: 382 eligible, 14 excluded",
    contextJson: { eligible: 382, excluded: 14 },
    createdBy: "system",
    createdAt: "2026-05-30T10:07:00Z",
  },
  {
    id: "log-015",
    jobId: DEMO_JOB_ID,
    stage: "scoring",
    level: "info",
    message: "Scoring complete: 382 candidates ranked",
    contextJson: { rankedCount: 382 },
    createdBy: "system",
    createdAt: "2026-05-30T10:08:00Z",
  },
  {
    id: "log-016",
    jobId: DEMO_JOB_ID,
    stage: "review",
    level: "info",
    message: "Review issues generated: 2 high, 7 medium, 14 low",
    contextJson: { high: 2, medium: 7, low: 14 },
    createdBy: "system",
    createdAt: "2026-05-30T10:30:00Z",
  },
  {
    id: "log-017",
    jobId: DEMO_JOB_ID,
    stage: "review",
    level: "warning",
    message: "High issue detected: unresolved canonical track for candidate #006",
    contextJson: { candidateId: "cand-006" },
    createdBy: "system",
    createdAt: "2026-05-30T10:30:00Z",
  },
  {
    id: "log-018",
    jobId: DEMO_JOB_ID,
    stage: "review",
    level: "warning",
    message: "High issue detected: unresolved canonical track for candidate #019",
    contextJson: { candidateId: "cand-019" },
    createdBy: "system",
    createdAt: "2026-05-30T10:31:00Z",
  },
];

export const mockEditions: ChartEdition[] = [
  {
    id: "ed-2026-w22",
    familyId: "fam-001",
    slug: "2026-week-22",
    label: "Week 22, 2026",
    date: "2026-05-30",
    periodStart: "2026-05-23",
    periodEnd: "2026-05-30",
    status: "published",
    ingestJobId: "job-002",
    publishedAt: "2026-05-30T12:30:00Z",
    publishedBy: "Sarah",
    entryCount: 100,
    newEntries: 5,
    reEntries: 2,
  },
  {
    id: "ed-2026-w21",
    familyId: "fam-001",
    slug: "2026-week-21",
    label: "Week 21, 2026",
    date: "2026-05-23",
    periodStart: "2026-05-16",
    periodEnd: "2026-05-23",
    status: "published",
    ingestJobId: "job-004",
    publishedAt: "2026-05-23T12:15:00Z",
    publishedBy: "James",
    entryCount: 40,
    newEntries: 3,
    reEntries: 1,
  },
  {
    id: "ed-2026-w22-afrobeats",
    familyId: "fam-003",
    slug: "2026-week-22-afrobeats",
    label: "Week 22, 2026",
    date: "2026-05-30",
    periodStart: "2026-05-23",
    periodEnd: "2026-05-30",
    status: "draft",
    ingestJobId: "job-003",
    publishedAt: null,
    publishedBy: null,
    entryCount: 0,
    newEntries: 0,
    reEntries: 0,
  },
];

export const mockSnapshots: Snapshot[] = [
  {
    id: "snap-001",
    editionId: "ed-2026-w22",
    familyId: "fam-002",
    snapshotJson: {
      edition: { id: "ed-2026-w22", label: "Week 22, 2026" },
      items: [],
      chartFamily: { id: "fam-002", label: "WAKILISHA Top 100" },
    },
    publishedAt: "2026-05-30T12:30:00Z",
    publishedBy: "Sarah",
  },
];

export const mockDashboardKpis: DashboardKpis = {
  activeJobs: 2,
  failedJobs: 1,
  pendingReviewIssues: 23,
  latestPublishedEdition: mockEditions[0],
  totalFamilies: 3,
  totalPublishedEditions: 2,
};

export function getFamilyById(id: string): ChartFamily | undefined {
  return mockChartFamilies.find((f) => f.id === id);
}

export function getJobById(id: string): IngestJob | undefined {
  const job = mockIngestJobs.find((j) => j.id === id);
  if (job) {
    return { ...job, chartFamily: getFamilyById(job.chartFamilyId) };
  }
  return undefined;
}

export function getSourcesForJob(jobId: string): IngestSource[] {
  return mockSources.filter((s) => s.jobId === jobId);
}

export function getRawItemsForJob(jobId: string): RawSourceItem[] {
  return mockRawItems.filter((r) => r.jobId === jobId);
}

export function getCandidatesForJob(jobId: string): IngestCandidate[] {
  return mockCandidates.filter((c) => c.jobId === jobId);
}

export function getMatchesForJob(jobId: string): IngestMatch[] {
  return mockMatches.filter((m) => m.jobId === jobId);
}

export function getIssuesForJob(jobId: string): ReviewIssue[] {
  return mockReviewIssues.filter((i) => i.jobId === jobId);
}

export function getDraftEntriesForJob(jobId: string): DraftEntry[] {
  return mockDraftEntries.filter((d) => d.jobId === jobId);
}

export function getLogsForJob(jobId: string): IngestJobLog[] {
  return mockLogs.filter((l) => l.jobId === jobId);
}

export const mockDiscoveredCsvs: DiscoveredCsvSource[] = [
  {
    id: "csv-disc-001",
    filename: "wakilisha_top_40_2026-05-30.csv",
    filepath: "data/supabase-imports/2026-05-30/raw/wakilisha_top_40_2026-05-30.csv",
    chartType: "top_40",
    confidence: "high",
    rowCount: 40,
    detectedDate: "2026-05-30",
    detectedWeek: "2026-W22",
    mappingStatus: "mapped",
    validationStatus: "valid",
    validationIssues: [],
    mappedFields: {
      rank: "rank",
      title: "track_title",
      artist_line: "artist_name",
      isrc: "isrc",
      release_title: "album",
      spotify_url: "spotify_url",
      youtube_url: "youtube_url",
      apple_music_url: "apple_music_url",
      artwork_url: "artwork_url",
      chart_week: "chart_week",
    },
    headers: [
      "rank",
      "track_title",
      "artist_name",
      "isrc",
      "spotify_url",
      "youtube_url",
      "apple_music_url",
      "artwork_url",
      "album",
      "label",
      "chart_week",
    ],
    sampleRows: [
      {
        rank: "1",
        track_title: "Love Me JeJe",
        artist_name: "Tems",
        isrc: "NGA0H2400001",
        spotify_url: "https://open.spotify.com/track/abc123",
        youtube_url: "https://youtube.com/watch?v=xyz789",
        apple_music_url: "https://music.apple.com/track/def456",
        artwork_url: "https://i.scdn.co/image/abc123",
        album: "Born in the Wild",
        label: "RCA Records",
        chart_week: "2026-W22",
      },
      {
        rank: "2",
        track_title: "Ojuelegba",
        artist_name: "WizKid",
        isrc: "USUM72012345",
        spotify_url: "https://open.spotify.com/track/wiz001",
        youtube_url: "https://youtube.com/watch?v=wiz002",
        apple_music_url: "https://music.apple.com/track/wiz003",
        artwork_url: "https://i.scdn.co/image/wiz001",
        album: "Ayo",
        label: "Starboy Entertainment",
        chart_week: "2026-W22",
      },
    ],
    usedAsSource: false,
    addedAt: null,
    provenance: [],
  },
  {
    id: "csv-disc-002",
    filename: "wakilisha_top_100_2026-05-30.csv",
    filepath: "data/supabase-imports/2026-05-30/raw/wakilisha_top_100_2026-05-30.csv",
    chartType: "top_100",
    confidence: "high",
    rowCount: 100,
    detectedDate: "2026-05-30",
    detectedWeek: "2026-W22",
    mappingStatus: "mapped",
    validationStatus: "valid",
    validationIssues: [],
    mappedFields: {
      rank: "position",
      title: "title",
      artist_line: "artist",
      isrc: "isrc",
      release_title: "album",
      spotify_url: "spotify_url",
      youtube_url: "youtube_url",
      apple_music_url: "apple_music_url",
      artwork_url: "artwork_url",
      chart_date: "chart_date",
    },
    headers: [
      "position",
      "title",
      "artist",
      "isrc",
      "spotify_url",
      "youtube_url",
      "apple_music_url",
      "artwork_url",
      "album",
      "chart_date",
    ],
    sampleRows: [
      {
        position: "1",
        title: "Love Me JeJe",
        artist: "Tems",
        isrc: "NGA0H2400001",
        spotify_url: "https://open.spotify.com/track/abc123",
        youtube_url: "https://youtube.com/watch?v=xyz789",
        apple_music_url: "https://music.apple.com/track/def456",
        artwork_url: "https://i.scdn.co/image/abc123",
        album: "Born in the Wild",
        chart_date: "2026-05-30",
      },
    ],
    usedAsSource: false,
    addedAt: null,
    provenance: [],
  },
  {
    id: "csv-disc-003",
    filename: "wakilisha_afrobeats_20_2026-05-30.csv",
    filepath: "data/supabase-imports/2026-05-30/raw/wakilisha_afrobeats_20_2026-05-30.csv",
    chartType: "afrobeats",
    confidence: "high",
    rowCount: 20,
    detectedDate: "2026-05-30",
    detectedWeek: "2026-W22",
    mappingStatus: "partial",
    validationStatus: "warnings",
    validationIssues: [
      "Missing YouTube URL column",
      "Missing Apple Music URL column",
      "Missing artwork_url column",
    ],
    mappedFields: {
      rank: "rank",
      title: "track",
      artist_line: "artist",
      isrc: "isrc",
      release_title: "release",
      spotify_url: "spotify_url",
      chart_week: "chart_week",
    },
    headers: ["rank", "track", "artist", "isrc", "spotify_url", "release", "chart_week"],
    sampleRows: [
      {
        rank: "1",
        track: "Calm Down",
        artist: "Rema",
        isrc: "NGA0H2300001",
        spotify_url: "https://open.spotify.com/track/rema001",
        release: "Rave & Roses",
        chart_week: "2026-W22",
      },
    ],
    usedAsSource: false,
    addedAt: null,
    provenance: [],
  },
  {
    id: "csv-disc-004",
    filename: "legacy_import_2026-05-30.csv",
    filepath: "data/supabase-imports/2026-05-30/raw/legacy_import_2026-05-30.csv",
    chartType: "generic_ranked",
    confidence: "medium",
    rowCount: 82,
    detectedDate: "2026-05-30",
    detectedWeek: "2026-W22",
    mappingStatus: "partial",
    validationStatus: "warnings",
    validationIssues: [
      "Missing ISRC column",
      "Missing Spotify URL column",
      "Missing artwork_url column",
      "Legacy notes column will be ignored",
    ],
    mappedFields: {
      rank: "position",
      title: "title",
      artist_line: "artist",
      label: "label",
    },
    headers: ["position", "title", "artist", "label", "notes"],
    sampleRows: [
      {
        position: "1",
        title: "Unknown Track",
        artist: "Unknown Artist",
        label: "Unknown Label",
        notes: "Legacy data \u2014 ISRC missing",
      },
    ],
    usedAsSource: false,
    addedAt: null,
    provenance: [],
  },
];

export function getDiscoveredCsvs(): DiscoveredCsvSource[] {
  return mockDiscoveredCsvs;
}

export function getDiscoveredCsvById(id: string): DiscoveredCsvSource | undefined {
  return mockDiscoveredCsvs.find((c) => c.id === id);
}