import type { WkDesignChapterSpec } from '../designSystemSpecTypes';

export const pageBlueprintChapters: WkDesignChapterSpec[] = [
  {
    id: 'charts-directory-page',
    number: '76',
    group: 'Page Blueprints',
    title: '/charts Directory Page',
    summary:
      'A commercially viable charts landing page blueprint with a strong charts hero, current #1 feature, active chart edition, chart series cards, archive table, movement signals, methodology/trust module, playable rail, sidebar modules, and a mobile-specific charts directory shell.',
    adminSections: [
      'Charts directory desktop preview',
      'Current #1 feature audit',
      'Series and archive table preview',
      'Signals and methodology preview',
      'Mobile charts directory preview',
      'Theme parity audit',
    ],
    implementationRules: [
      'Use cdir-* classes from wakilisha.elements.charts-directory.css for the desktop /charts landing page.',
      'Use mob-cdir-* classes for the mobile /charts landing page shell.',
      'The page must be registry/API-backed: chart series, editions, #1 track, movements, weeks, sources, and archive rows must come from real chart data.',
      'Do not hard-lock the page to dark mode. Components follow active design tokens unless text sits on a fixed image overlay.',
      'Only image overlays and artwork-hover play buttons may use fixed white/dark contrast values for legibility.',
      'The /charts directory is not the same as a chart edition page; it must help users understand active charts, historical archive, movement signals, and methodology.',
    ],
    componentsRequired: [
      'WkChartsDirectoryPage',
      'WkChartsDirectoryHero',
      'WkChartsCurrentNumberOne',
      'WkChartsFeatureBlock',
      'WkChartSeriesGrid',
      'WkChartsArchiveTable',
      'WkChartsSignalCards',
      'WkChartsMethodologyCard',
      'WkChartsPlayableRail',
      'WkChartsSidebarCard',
      'WkMobileChartsDirectory',
      '.cdir-layout',
      '.cdir-hero',
      '.cdir-hero-no1',
      '.cdir-feature',
      '.cdir-top1',
      '.cdir-row',
      '.cdir-series-grid',
      '.cseries-card',
      '.cdir-archive',
      '.cdir-signals',
      '.csignal-card',
      '.cdir-method',
      '.cdir-play-rail',
      '.cdir-sidebar-card',
      '.mob-cdir',
    ],
    tables: ['chart_series', 'chart_editions', 'chart_entries', 'tracks', 'track_artists', 'media_assets'],
    parityTargets: [
      'Build /charts as a full charts directory, not a flat list or duplicated chart-edition page.',
      'Current #1 block uses real top entry from the latest active chart edition.',
      'Series cards expose active/archived/experimental chart status and latest #1 track.',
      'Archive table shows editions with period, #1 track, entry count, source count, and access state.',
      'Signals section shows climbers, new entries, and long runners from movement data.',
      'Methodology module explains how the chart is compiled using real source metadata.',
      'Mobile /charts uses the mob-cdir layout and keeps bottom nav / mini-player safe areas clear.',
      'Light mode has no leaked dark-mode surfaces except fixed media overlays.',
    ],
    qaChecks: [
      { id: '76-directory-not-edition', label: 'Directory not edition', description: '/charts explains the chart universe and archive, not only one ranked list.' },
      { id: '76-data-backed', label: 'Data-backed', description: 'All series, entries, movement, weeks, archive and methodology content comes from real chart data.' },
      { id: '76-current-no1', label: 'Current #1', description: 'The hero/current feature renders the latest active chart #1 with artwork and artist attribution.' },
      { id: '76-series-clear', label: 'Series clear', description: 'Chart series cards distinguish active, archived and experimental series.' },
      { id: '76-archive-usable', label: 'Archive usable', description: 'Archive rows include period, edition, #1, entries, sources and access state.' },
      { id: '76-signals-real', label: 'Signals real', description: 'Climbers, new entries and long runners are calculated from movement data, not fabricated.' },
      { id: '76-methodology-visible', label: 'Methodology visible', description: 'The page clearly explains chart sources and compilation logic.' },
      { id: '76-theme-tokenized', label: 'Theme tokenized', description: 'Light/dark mode follows design tokens; no product component is hard-locked to the wrong theme.' },
      { id: '76-mobile-specific', label: 'Mobile specific', description: 'Mobile uses the dedicated mob-cdir pattern instead of collapsed desktop.' },
    ],
  },
];
